In [1]:
# from monai.transforms import Compose, LoadImage
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data0 = pd.read_csv("/projects/net_contrast_classification/contrast_phase/total_seg_output/contrast_phase_results_batch0.csv")
data1 = pd.read_csv("/projects/net_contrast_classification/contrast_phase/total_seg_output/contrast_phase_results_batch1.csv")
data2 = pd.read_csv("/projects/net_contrast_classification/contrast_phase/total_seg_output/contrast_phase_results_batch2.csv")
data3 = pd.read_csv("/projects/net_contrast_classification/contrast_phase/total_seg_output/contrast_phase_results_batch3.csv")


data1

,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,file
0,80.03,portal_venous,1.0,77.84,81.19,1.1685,NKI-d23231-00-0145_20070620_kalina99_0212.nii.gz
1,82.57,portal_venous,1.0,81.59,83.29,0.6462,NKI-d23231-00-0145_20071002_kalina99_0213.nii.gz
2,56.70,arterial_late,0.7,49.31,65.95,5.6282,NKI-d23231-00-0145_20080304_kalina99_0215.nii.gz
3,77.27,portal_venous,1.0,76.32,79.26,1.0410,NKI-d23231-00-0145_20080304_kalina99_0216.nii.gz
4,50.59,arterial_late,0.7,44.67,54.72,3.5907,NKI-d23231-00-0145_20090916_kalina99_0217.nii.gz
...,...,...,...,...,...,...,...
1388,76.10,portal_venous,1.0,75.12,78.47,1.2102,NKI-d23231-00-0292_20150407_kalina99_1135.nii.gz
1389,47.73,arterial_late,1.0,43.38,52.07,3.1476,NKI-d23231-00-0292_20150407_kalina99_1136.nii.gz
1390,77.90,portal_venous,1.0,76.26,80.24,1.3613,NKI-d23231-00-0292_20151026_kalina99_1137.nii.gz
1391,48.78,arterial_late,1.0,43.92,52.95,3.1085,NKI-d23231-00-0292_20151026_kalina99_1138.nii.gz
1392,56.37,arterial_late,0.7,52.36,62.29,3.5034,NKI-d23231-00-0292_20160519_kalina99_1140.nii.gz

In [3]:
ts_data = pd.concat([data0, data1, data2, data3])
ts_data   # Error processing /mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/NKI-d23231-00-0818_20190322_kalina99_5441.nii.gz: Command '['totalseg_get_phase', '-i', np.str_('/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/NKI-d23231-00-0818_20190322_kalina99_5441.nii.gz'), '-o', '/projects/net_contrast_classification/contrast_phase/total_seg_output/NKI-d23231-00-0818_20190322_kalina99_5441_phase.json']' returned non-zero exit status 1.

,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,file
0,62.02,portal_venous,1.0,56.91,66.18,3.0706,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz
1,78.87,portal_venous,1.0,76.97,80.38,1.1980,NKI-d23231-00-0036_20140218_kalina01_0002.nii.gz
2,69.99,portal_venous,1.0,67.83,72.74,1.7276,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz
3,74.84,portal_venous,1.0,66.55,82.59,5.8700,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz
4,73.99,portal_venous,1.0,73.19,75.08,0.7242,NKI-d23231-00-0049_20090212_kalina01_0005.nii.gz
...,...,...,...,...,...,...,...
1387,80.39,portal_venous,1.0,78.27,82.66,1.4937,NKI-d23231-00-0888_20220420_kalina99_5827.nii.gz
1388,59.19,arterial_late,0.7,56.14,61.54,1.8509,NKI-d23231-00-0888_20230424_kalina99_5828.nii.gz
1389,77.28,portal_venous,1.0,74.66,78.94,1.6271,NKI-d23231-00-0888_20230424_kalina99_5829.nii.gz
1390,63.08,portal_venous,1.0,60.32,64.76,1.5287,NKI-d23231-00-0888_20230801_kalina99_5830.nii.gz
1391,73.31,portal_venous,1.0,72.83,73.69,0.2884,NKI-d23231-00-0888_20230801_kalina99_5831.nii.gz

In [4]:
from pathlib import PureWindowsPath
import os

data = pd.read_csv("/projects/net_contrast_classification/contrast_phase/dataset-registration-artinet.csv")
data["file0"] = data["file"]
data["file"] = data["NiiFile"].apply(lambda x: PureWindowsPath(x).name)
data["ExamDate"] = data["ExamDate"].apply(lambda x: pd.to_datetime(x))
data

,SubjectKeyRadiology,ExamDate,SegmentationBatch,NiiFile,SegNiiFile,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,...,ConvolutionKernel,ExposureTime,XRayTubeCurrent,XRayExposure,ImageOrientationPatientDICOM,ConversionSoftware,ConversionSoftwareVersion,BodyPartExamined,RawImage,file0
0,NKI-d23231-00-0063,2012-04-16,kalina01_0000,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz,Partially,Arterial,Too Early,No,...,FC02,0.5,150,75,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,NaN,NaN,NET_0000_0000.nii.gz
1,NKI-d23231-00-0036,2014-02-18,kalina01_0002,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0036_20140218_kalina01_0002.nii.gz,Yes,Portal,Just Right,Yes,...,FC01,0.5,75,37,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,NaN,NaN,NET_0002_0000.nii.gz
2,NKI-d23231-00-0071,2013-09-24,kalina01_0003,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz,Yes,Arterial,Just Right,Yes,...,B30f,0.5,168,84,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_0003_0000.nii.gz
3,NKI-d23231-00-0077,2014-12-22,kalina01_0004,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz,Yes,Portal,Just Right,No,...,B25f,0.5,119,74,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_0004_0000.nii.gz
4,NKI-d23231-00-0049,2009-02-12,kalina01_0005,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0049_20090212_kalina01_0005.nii.gz,Yes,Portal,Just Right,Yes,...,B25f,0.5,280,140,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_0005_0000.nii.gz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,NKI-d23231-00-0888,2022-04-20,kalina99_5827,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0888_20220420_kalina99_5827.nii.gz,Yes,Portal,Just Right,No,...,B25f,0.5,158,98,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_5827_0000.nii.gz
5568,NKI-d23231-00-0888,2023-04-24,kalina99_5828,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0888_20230424_kalina99_5828.nii.gz,Yes,Arterial,Just Right,Yes,...,Bv38f\2,0.5,316,175,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_5828_0000.nii.gz
5569,NKI-d23231-00-0888,2023-04-24,kalina99_5829,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0888_20230424_kalina99_5829.nii.gz,Yes,Portal,Just Right,No,...,Bv38f\2,0.5,304,168,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_5829_0000.nii.gz
5570,NKI-d23231-00-0888,2023-08-01,kalina99_5830,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0888_20230801_kalina99_5830.nii.gz,Yes,Arterial,Just Right,Yes,...,Bv38f\2,0.5,167,92,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_5830_0000.nii.gz
5571,NKI-d23231-00-0888,2023-08-01,kalina99_5831,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0888_20230801_kalina99_5831.nii.gz,Yes,Portal,Just Right,Yes,...,Bv38f\2,0.5,203,112,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,NET_5831_0000.nii.gz

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 43 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   SubjectKeyRadiology                 5572 non-null   str
 1   ExamDate                            5572 non-null   datetime64[us]
 2   SegmentationBatch                   5572 non-null   str
 3   NiiFile                             5572 non-null   str
 4   SegNiiFile                          5572 non-null   str
 5   file                                5572 non-null   str
 6   is_liver_imaged                     5572 non-null   str
 7   contrast                            5454 non-null   str
 8   phase_timing                        5454 non-null   str
 9   is_lesionfree                       5572 non-null   str
 10  ai_segmentation_quality             3498 non-null   float64
 11  manual_segmentation_confidence      3498 non-null   float64
 12  adjustment_segmentation_difficulty  3498 non-null   float64
 13  high_signal_to_noise                5454 non-null   object
 14  metal_artifacts                     5454 non-null   object
 15  patient_motion                      5454 non-null   object
 16  other                               0 non-null      float64
 17  comment                             0 non-null      float64
 18  time-stamp                          5572 non-null   int64
 19  Modality                            5572 non-null   str
 20  ImagingFrequency                    5572 non-null   int64
 21  Manufacturer                        5572 non-null   str
 22  ManufacturersModelName              5572 non-null   str
 23  DeviceSerialNumber                  5356 non-null   float64
 24  PatientPosition                     5572 non-null   str
 25  SoftwareVersions                    5572 non-null   str
 26  SeriesDescription                   5572 non-null   str
 27  ProtocolName                        5572 non-null   str
 28  ScanOptions                         2721 non-null   str
 29  ImageType                           5572 non-null   str
 30  SeriesNumber                        5572 non-null   int64
 31  AcquisitionTime                     5572 non-null   str
 32  AcquisitionNumber                   5389 non-null   float64
 33  ConvolutionKernel                   5572 non-null   str
 34  ExposureTime                        5392 non-null   float64
 35  XRayTubeCurrent                     5572 non-null   int64
 36  XRayExposure                        5572 non-null   int64
 37  ImageOrientationPatientDICOM        5572 non-null   str
 38  ConversionSoftware                  5572 non-null   str
 39  ConversionSoftwareVersion           5572 non-null   str
 40  BodyPartExamined                    4058 non-null   str
 41  RawImage                            12 non-null     object
 42  file0                               5572 non-null   str
dtypes: datetime64[us](1), float64(8), int64(5), object(4), str(25)
memory usage: 4.6+ MB

In [6]:
data.dropna(axis=0, how='all')
data = data.drop(columns=['other', 'comment', 'RawImage'])
data.dropna(subset=["contrast"], inplace=True, ignore_index=True)  # 118 entries with unknown phase removed
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5454 entries, 0 to 5453
Data columns (total 40 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   SubjectKeyRadiology                 5454 non-null   str
 1   ExamDate                            5454 non-null   datetime64[us]
 2   SegmentationBatch                   5454 non-null   str
 3   NiiFile                             5454 non-null   str
 4   SegNiiFile                          5454 non-null   str
 5   file                                5454 non-null   str
 6   is_liver_imaged                     5454 non-null   str
 7   contrast                            5454 non-null   str
 8   phase_timing                        5454 non-null   str
 9   is_lesionfree                       5454 non-null   str
 10  ai_segmentation_quality             3498 non-null   float64
 11  manual_segmentation_confidence      3498 non-null   float64
 12  adjustment_segmentation_difficulty  3498 non-null   float64
 13  high_signal_to_noise                5454 non-null   object
 14  metal_artifacts                     5454 non-null   object
 15  patient_motion                      5454 non-null   object
 16  time-stamp                          5454 non-null   int64
 17  Modality                            5454 non-null   str
 18  ImagingFrequency                    5454 non-null   int64
 19  Manufacturer                        5454 non-null   str
 20  ManufacturersModelName              5454 non-null   str
 21  DeviceSerialNumber                  5244 non-null   float64
 22  PatientPosition                     5454 non-null   str
 23  SoftwareVersions                    5454 non-null   str
 24  SeriesDescription                   5454 non-null   str
 25  ProtocolName                        5454 non-null   str
 26  ScanOptions                         2696 non-null   str
 27  ImageType                           5454 non-null   str
 28  SeriesNumber                        5454 non-null   int64
 29  AcquisitionTime                     5454 non-null   str
 30  AcquisitionNumber                   5277 non-null   float64
 31  ConvolutionKernel                   5454 non-null   str
 32  ExposureTime                        5279 non-null   float64
 33  XRayTubeCurrent                     5454 non-null   int64
 34  XRayExposure                        5454 non-null   int64
 35  ImageOrientationPatientDICOM        5454 non-null   str
 36  ConversionSoftware                  5454 non-null   str
 37  ConversionSoftwareVersion           5454 non-null   str
 38  BodyPartExamined                    3959 non-null   str
 39  file0                               5454 non-null   str
dtypes: datetime64[us](1), float64(6), int64(5), object(3), str(25)
memory usage: 4.4+ MB

In [35]:
from pathlib import PureWindowsPath
import os

merged_data = pd.merge(data, ts_data, on=["file"])

print("True phase labels:\n", merged_data["contrast"].value_counts())
print("\n")
print("True timing labels:\n",merged_data["phase_timing"].value_counts())
print('\n')
print("TS labels:\n",merged_data["phase"].value_counts())

True phase labels:
 contrast
Portal        3281
Arterial      2123
0               42
Late Phase       7
Name: count, dtype: int64


True timing labels:
 phase_timing
Just Right    4506
Too Early      759
Too Late       151
0               37
Name: count, dtype: int64


TS labels:
 phase
portal_venous     3929
arterial_late     1482
native              30
arterial_early      12
Name: count, dtype: int64

In [36]:
merged_data[
    ((merged_data['contrast'] == '0') & (merged_data['phase_timing'] != '0'))|
    ((merged_data['contrast'] != '0') & (merged_data['phase_timing'] == '0'))
]

,SubjectKeyRadiology,ExamDate,SegmentationBatch,NiiFile,SegNiiFile,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,...,ConversionSoftware,ConversionSoftwareVersion,BodyPartExamined,file0,pi_time,phase,probability,pi_time_min,pi_time_max,stddev
1440,NKI-d23231-00-0161,2005-08-04,kalina99_0367,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0161_20050804_kalina99_0367.nii.gz,Yes,Arterial,0,Yes,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_0367_0000.nii.gz,48.63,arterial_late,1.0,37.58,63.00,9.0587
1488,NKI-d23231-00-0170,2006-04-05,kalina99_0444,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0170_20060405_kalina99_0444.nii.gz,Yes,0,Just Right,No,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_0444_0000.nii.gz,82.13,portal_venous,1.0,77.66,87.60,3.8453
1602,NKI-d23231-00-0193,2016-10-12,kalina99_0660,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0193_20161012_kalina99_0660.nii.gz,Yes,0,Too Early,No,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_0660_0000.nii.gz,77.88,portal_venous,1.0,75.51,80.96,1.7601
2107,NKI-d23231-00-0218,2016-04-20,kalina99_0212,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0218_20160420_kalina99_0212.nii.gz,Yes,0,Just Right,No,...,dcm2niix,v1.0.20230411,CHEST,NET_0212_0000.nii.gz,80.22,portal_venous,1.0,73.56,82.55,3.3697
2569,NKI-d23231-00-0278,2014-06-25,kalina99_0892,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0278_20140625_kalina99_0892.nii.gz,Yes,0,Just Right,No,...,dcm2niix,v1.0.20230411,NaN,NET_0892_0000.nii.gz,78.08,portal_venous,1.0,75.56,81.19,2.3187
3606,NKI-d23231-00-0415,2014-01-08,kalina99_2664,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0415_20140108_kalina99_2664.nii.gz,Yes,0,Just Right,No,...,dcm2niix,v1.0.20230411,NaN,NET_2664_0000.nii.gz,44.70,arterial_late,1.0,41.32,49.73,3.0547
4167,NKI-d23231-00-0532,2015-08-18,kalina99_3669,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0532_20150818_kalina99_3669.nii.gz,Yes,0,Just Right,No,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_3669_0000.nii.gz,81.06,portal_venous,1.0,78.78,83.38,1.7551
4393,NKI-d23231-00-0576,2011-12-05,kalina99_4114,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0576_20111205_kalina99_4114.nii.gz,Yes,Portal,0,No,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_4114_0000.nii.gz,76.75,portal_venous,1.0,74.48,78.64,1.4875
4958,NKI-d23231-00-0772,2021-01-21,kalina99_5143,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0772_20210121_kalina99_5143.nii.gz,Yes,0,Just Right,No,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_5143_0000.nii.gz,47.34,arterial_late,1.0,42.55,54.87,4.4363
5143,NKI-d23231-00-0814,2019-04-03,kalina99_5412,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0814_20190403_kalina99_5412.nii.gz,Yes,Arterial,0,No,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_5412_0000.nii.gz,67.64,portal_venous,1.0,65.54,70.08,1.5131
5228,NKI-d23231-00-0829,2020-11-18,kalina99_5525,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0829_20201118_kalina99_5525.nii.gz,0,0,Just Right,Yes,...,dcm2niix,v1.0.20230411,ABDOMEN,NET_5525_0000.nii.gz,83.88,portal_venous,1.0,79.84,90.23,3.6458

In [37]:
# 0 => NC for phase and timing
merged_data["contrast"] = merged_data["contrast"].apply(lambda x: 'Non-contrast' if x == '0' else x)        
merged_data["phase_timing"] = merged_data["phase_timing"].apply(lambda x: 'Non-contrast' if x == '0' else x)

# Create TS phase
merged_data["TS_contrast"] = merged_data["phase"].apply(lambda x: x.split("_")[0].capitalize() if "_" in x else 'Non-contrast')

merged_data["TS_timing"] = merged_data["phase"].apply(lambda x: x.split("_")[1].capitalize() if "_" in x else "Non-contrast")
merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Just Right" if x == 'Venous' else x)
merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Too Early" if x == 'Early' else x)
merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Too Late" if x == 'Late' else x)


merged_data.loc[merged_data["contrast"] == "Non-contrast","phase_timing"] = "Non-contrast"
mask = (
    merged_data["contrast"] != "Non-contrast"
) & (
    merged_data["phase_timing"] == "Non-contrast"
)

merged_data.loc[mask, "phase_timing"] = "Just Right"



merged_data = merged_data[merged_data["contrast"] != "Late Phase"]  # 7 entries removed 

print("\n")
print('After renaming:')
print("True labels:\n", merged_data["contrast"].value_counts())
print("\n")
print("TS labels:\n",merged_data["TS_contrast"].value_counts())

print("\n\n")

print("True timing labels:\n", merged_data["phase_timing"].value_counts())
print("\n")
print("TS timing labels:\n",merged_data["TS_timing"].value_counts())

After renaming:
True labels:
 contrast
Portal          3281
Arterial        2123
Non-contrast      42
Name: count, dtype: int64


TS labels:
 TS_contrast
Portal          3922
Arterial        1494
Non-contrast      30
Name: count, dtype: int64



True timing labels:
 phase_timing
Just Right      4498
Too Early        758
Too Late         148
Non-contrast      42
Name: count, dtype: int64


TS timing labels:
 TS_timing
Just Right      3922
Too Late        1482
Non-contrast      30
Too Early         12
Name: count, dtype: int64

## Arterial vs. Portal vs. NC

In [38]:
merged_data.head(5)

,SubjectKeyRadiology,ExamDate,SegmentationBatch,NiiFile,SegNiiFile,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,...,BodyPartExamined,file0,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,TS_contrast,TS_timing
0,NKI-d23231-00-0063,2012-04-16,kalina01_0000,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz,Partially,Arterial,Too Early,No,...,NaN,NET_0000_0000.nii.gz,62.02,portal_venous,1.0,56.91,66.18,3.0706,Portal,Just Right
1,NKI-d23231-00-0036,2014-02-18,kalina01_0002,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0036_20140218_kalina01_0002.nii.gz,Yes,Portal,Just Right,Yes,...,NaN,NET_0002_0000.nii.gz,78.87,portal_venous,1.0,76.97,80.38,1.1980,Portal,Just Right
2,NKI-d23231-00-0071,2013-09-24,kalina01_0003,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz,Yes,Arterial,Just Right,Yes,...,ABDOMEN,NET_0003_0000.nii.gz,69.99,portal_venous,1.0,67.83,72.74,1.7276,Portal,Just Right
3,NKI-d23231-00-0077,2014-12-22,kalina01_0004,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz,Yes,Portal,Just Right,No,...,ABDOMEN,NET_0004_0000.nii.gz,74.84,portal_venous,1.0,66.55,82.59,5.8700,Portal,Just Right
4,NKI-d23231-00-0049,2009-02-12,kalina01_0005,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0049_20090212_kalina01_0005.nii.gz,Yes,Portal,Just Right,Yes,...,ABDOMEN,NET_0005_0000.nii.gz,73.99,portal_venous,1.0,73.19,75.08,0.7242,Portal,Just Right

In [51]:
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_true = le.fit_transform(merged_data["contrast"])
y_pred = le.fit_transform(merged_data['TS_contrast'])

print('Contrast classification accuracy:', round(accuracy_score(y_true, y_pred),3))
print("Classification report:", classification_report(y_true, y_pred, target_names=le.classes_))

Contrast classification accuracy: 0.874
Classification report:               precision    recall  f1-score   support

    Arterial       0.99      0.69      0.81      2123
Non-contrast       0.93      0.67      0.78        42
      Portal       0.83      0.99      0.91      3281

    accuracy                           0.87      5446
   macro avg       0.92      0.78      0.83      5446
weighted avg       0.89      0.87      0.87      5446

In [40]:
misclassified = merged_data[
    merged_data['contrast'] != merged_data['TS_contrast']
]
misclassified

,SubjectKeyRadiology,ExamDate,SegmentationBatch,NiiFile,SegNiiFile,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,...,BodyPartExamined,file0,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,TS_contrast,TS_timing
0,NKI-d23231-00-0063,2012-04-16,kalina01_0000,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz,Partially,Arterial,Too Early,No,...,NaN,NET_0000_0000.nii.gz,62.02,portal_venous,1.0,56.91,66.18,3.0706,Portal,Just Right
2,NKI-d23231-00-0071,2013-09-24,kalina01_0003,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz,Yes,Arterial,Just Right,Yes,...,ABDOMEN,NET_0003_0000.nii.gz,69.99,portal_venous,1.0,67.83,72.74,1.7276,Portal,Just Right
23,NKI-d23231-00-0006,2015-02-09,kalina01_0041,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0006_20150209_kalina01_0041.nii.gz,Yes,Arterial,Just Right,Yes,...,NaN,NET_0041_0000.nii.gz,62.98,portal_venous,1.0,60.28,66.94,2.7831,Portal,Just Right
26,NKI-d23231-00-0040,2015-05-18,kalina01_0049,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0040_20150518_kalina01_0049.nii.gz,Yes,Arterial,Just Right,No,...,NaN,NET_0049_0000.nii.gz,61.43,portal_venous,1.0,59.96,66.98,2.7743,Portal,Just Right
31,NKI-d23231-00-0095,2011-09-01,kalina01_0054,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0095_20110901_kalina01_0054.nii.gz,Yes,Arterial,Too Late,No,...,ABDOMEN,NET_0054_0000.nii.gz,65.40,portal_venous,1.0,60.61,71.02,3.7450,Portal,Just Right
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5402,NKI-d23231-00-0875,2023-08-02,kalina99_5760,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0875_20230802_kalina99_5760.nii.gz,Yes,Arterial,Just Right,No,...,ABDOMEN,NET_5760_0000.nii.gz,66.60,portal_venous,1.0,65.59,68.29,0.9629,Portal,Just Right
5412,NKI-d23231-00-0879,2021-09-29,kalina99_5775,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0879_20210929_kalina99_5775.nii.gz,Yes,Arterial,Just Right,Yes,...,ABDOMEN,NET_5775_0000.nii.gz,62.41,portal_venous,1.0,60.82,64.50,1.2733,Portal,Just Right
5433,NKI-d23231-00-0882,2022-08-29,kalina99_5801,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0882_20220829_kalina99_5801.nii.gz,Yes,Arterial,Just Right,Yes,...,ABDOMEN,NET_5801_0000.nii.gz,60.33,portal_venous,1.0,53.97,67.14,4.2907,Portal,Just Right
5440,NKI-d23231-00-0887,2021-08-25,kalina99_5811,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0887_20210825_kalina99_5811.nii.gz,Yes,Arterial,Just Right,No,...,ABDOMEN,NET_5811_0000.nii.gz,60.58,portal_venous,1.0,56.17,67.01,3.6689,Portal,Just Right
5451,NKI-d23231-00-0888,2023-08-01,kalina99_5830,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0888_20230801_kalina99_5830.nii.gz,Yes,Arterial,Just Right,Yes,...,ABDOMEN,NET_5830_0000.nii.gz,63.08,portal_venous,1.0,60.32,64.76,1.5287,Portal,Just Right

In [41]:
print("Confusion matrix:")
pd.crosstab(
    merged_data['contrast'],
    merged_data['TS_contrast'],
    margins=True
)

Confusion matrix:

TS_contrast   Arterial  Non-contrast  Portal   All
contrast
Arterial          1473             0     650  2123
Non-contrast         3            28      11    42
Portal              18             2    3261  3281
All               1494            30    3922  5446

In [42]:
merged_data.columns

Index(['SubjectKeyRadiology', 'ExamDate', 'SegmentationBatch', 'NiiFile',
       'SegNiiFile', 'file', 'is_liver_imaged', 'contrast', 'phase_timing',
       'is_lesionfree', 'ai_segmentation_quality',
       'manual_segmentation_confidence', 'adjustment_segmentation_difficulty',
       'high_signal_to_noise', 'metal_artifacts', 'patient_motion',
       'time-stamp', 'Modality', 'ImagingFrequency', 'Manufacturer',
       'ManufacturersModelName', 'DeviceSerialNumber', 'PatientPosition',
       'SoftwareVersions', 'SeriesDescription', 'ProtocolName', 'ScanOptions',
       'ImageType', 'SeriesNumber', 'AcquisitionTime', 'AcquisitionNumber',
       'ConvolutionKernel', 'ExposureTime', 'XRayTubeCurrent', 'XRayExposure',
       'ImageOrientationPatientDICOM', 'ConversionSoftware',
       'ConversionSoftwareVersion', 'BodyPartExamined', 'file0', 'pi_time',
       'phase', 'probability', 'pi_time_min', 'pi_time_max', 'stddev',
       'TS_contrast', 'TS_timing'],
      dtype='str')

In [43]:
misclassified[['SubjectKeyRadiology', 'ExamDate','file', 'is_liver_imaged',
                'contrast', 'phase_timing','high_signal_to_noise',
                'metal_artifacts','AcquisitionTime', 'ProtocolName',
                'TS_contrast', 'TS_timing', 'pi_time', 'probability', 'pi_time_min',
                'pi_time_max', 'stddev']].sort_values(by=['SubjectKeyRadiology', 'ExamDate'], ascending=[True, True])

,SubjectKeyRadiology,ExamDate,file,is_liver_imaged,contrast,phase_timing,high_signal_to_noise,metal_artifacts,AcquisitionTime,ProtocolName,TS_contrast,TS_timing,pi_time,probability,pi_time_min,pi_time_max,stddev
461,NKI-d23231-00-0001,2012-06-19,NKI-d23231-00-0001_20120619_kalina12_0027.nii.gz,Yes,Arterial,Too Late,False,False,27:59.2,ABDOMEN + C 1.0 FC02,Portal,Just Right,79.05,1.0,78.15,80.64,0.9401
70,NKI-d23231-00-0002,2015-12-01,NKI-d23231-00-0002_20151201_kalina02_0051.nii.gz,Yes,Arterial,Too Late,False,False,03:50.2,Maag.abdomen 1.5 B25f,Portal,Just Right,60.74,1.0,57.24,65.44,2.9675
332,NKI-d23231-00-0005,2015-08-04,NKI-d23231-00-0005_20150804_kalina15_0021.nii.gz,Yes,Arterial,Just Right,False,False,10:30.9,ABDOMEN + C 1.0 FC01,Portal,Just Right,71.92,1.0,69.64,74.95,1.7549
72,NKI-d23231-00-0005,2022-10-17,NKI-d23231-00-0005_20221017_kalina02_0055.nii.gz,Yes,Arterial,Just Right,False,False,18:44.4,Abd laat-art 1.0 Bv38 2,Portal,Just Right,67.70,1.0,63.97,73.61,3.5886
449,NKI-d23231-00-0006,2014-05-30,NKI-d23231-00-0006_20140530_kalina12_0007.nii.gz,Yes,Arterial,Just Right,False,False,05:37.2,ABDOMEN A 1.0 FC01,Portal,Just Right,67.87,1.0,64.70,72.44,3.1755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5412,NKI-d23231-00-0879,2021-09-29,NKI-d23231-00-0879_20210929_kalina99_5775.nii.gz,Yes,Arterial,Just Right,False,False,22:34.0,Abd laat-art 1.0 Bv38 2,Portal,Just Right,62.41,1.0,60.82,64.50,1.2733
1977,NKI-d23231-00-0879,2022-05-18,NKI-d23231-00-0879_20220518_kalina01_0517.nii.gz,Yes,Arterial,Just Right,False,False,07:09.9,Abd laat-art 1.0 Bv38 2,Portal,Just Right,64.55,1.0,63.11,66.91,1.3455
5433,NKI-d23231-00-0882,2022-08-29,NKI-d23231-00-0882_20220829_kalina99_5801.nii.gz,Yes,Arterial,Just Right,False,False,56:41.6,Abd laat-art 1.0 Bv38 2,Portal,Just Right,60.33,1.0,53.97,67.14,4.2907
5440,NKI-d23231-00-0887,2021-08-25,NKI-d23231-00-0887_20210825_kalina99_5811.nii.gz,Yes,Arterial,Just Right,False,False,31:51.5,Abdomen A 1.5 B25f,Portal,Just Right,60.58,1.0,56.17,67.01,3.6689
5451,NKI-d23231-00-0888,2023-08-01,NKI-d23231-00-0888_20230801_kalina99_5830.nii.gz,Yes,Arterial,Just Right,False,False,43:20.6,Abd laat-art 1.0 Bv38 2,Portal,Just Right,63.08,1.0,60.32,64.76,1.5287

## Phase + Timing Classification Results

In [54]:
# merged_data.loc[merged_data["contrast"] == "Portal","phase_timing"] = "Just Right"

merged_data["phase_timing_combined"] = (merged_data["contrast"].str.cat(merged_data["phase_timing"], sep=" "))
merged_data["TS_phase_timing_combined"] = (merged_data["TS_contrast"].str.cat(merged_data["TS_timing"], sep=" "))

print(merged_data["phase_timing_combined"].value_counts())
print("\n")
print(merged_data["TS_phase_timing_combined"].value_counts())

phase_timing_combined
Portal Just Right            3133
Arterial Just Right          1365
Arterial Too Early            661
Arterial Too Late              97
Portal Too Early               97
Portal Too Late                51
Non-contrast Non-contrast      42
Name: count, dtype: int64


TS_phase_timing_combined
Portal Just Right            3922
Arterial Too Late            1482
Non-contrast Non-contrast      30
Arterial Too Early             12
Name: count, dtype: int64

In [55]:
y_true = le.fit_transform(merged_data["phase_timing"])
y_pred = le.fit_transform(merged_data['TS_timing'])

print('Timing classification accuracy:', round(accuracy_score(y_true, y_pred),3))
print("Classification report:\n", classification_report(y_true, y_pred, target_names=le.classes_))

Timing classification accuracy: 0.67
Classification report:
               precision    recall  f1-score   support

  Just Right       0.92      0.80      0.85      4498
Non-contrast       0.93      0.67      0.78        42
   Too Early       0.50      0.01      0.02       758
    Too Late       0.01      0.12      0.02       148

    accuracy                           0.67      5446
   macro avg       0.59      0.40      0.42      5446
weighted avg       0.84      0.67      0.71      5446

In [56]:
contrast_correct = merged_data[merged_data["contrast"] == merged_data["TS_contrast"]].copy()

y_true = le.fit_transform(contrast_correct["phase_timing"])
y_pred = le.fit_transform(contrast_correct['TS_timing'])

print('Timing classification accuracy:', round(accuracy_score(y_true, y_pred),3))
print("Classification report:\n", classification_report(y_true, y_pred, target_names=le.classes_))

Timing classification accuracy: 0.665
Classification report:
               precision    recall  f1-score   support

  Just Right       0.96      0.78      0.86      3996
Non-contrast       1.00      1.00      1.00        28
   Too Early       0.55      0.01      0.02       669
    Too Late       0.01      0.26      0.02        69

    accuracy                           0.67      4762
   macro avg       0.63      0.51      0.47      4762
weighted avg       0.88      0.67      0.73      4762