# TotalSegmentator Baseline

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import os

## Data Loading

### TS results

In [2]:
folder = "/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/"

radiomics = pd.DataFrame()
for subdir in os.listdir(folder):
    for file_path in os.listdir(os.path.join(folder, subdir)):
        if file_path != "jsons":
            print(file_path)

contrast_phase_results_batch3.csv
contrast_phase_results_batch2.csv
contrast_phase_results_batch1.csv
contrast_phase_results_batch0.csv
contrast_phase_results_batch3.csv
contrast_phase_results_batch2.csv
contrast_phase_results_batch1.csv
contrast_phase_results_batch0.csv

In [3]:
folder = "/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/"

dfs = []
for subdir in os.listdir(folder):
    for file_path in os.listdir(os.path.join(folder, subdir)):
        if file_path != "jsons":
            data = pd.read_csv(os.path.join(folder, subdir, file_path))
            dfs.append(data)

ts_data = pd.concat(dfs, ignore_index=True)
ts_data   # Error processing /mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/NKI-d23231-00-0818_20190322_kalina99_5441.nii.gz: Command '['totalseg_get_phase', '-i', np.str_('/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/NKI-d23231-00-0818_20190322_kalina99_5441.nii.gz'), '-o', '/projects/net_contrast_classification/contrast_phase/total_seg_output/NKI-d23231-00-0818_20190322_kalina99_5441_phase.json']' returned non-zero exit status 1.
          # Error processing /mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20100107_kalina99_0195.nii.gz: Command '['totalseg_get_phase', '-i', np.str_('/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20100107_kalina99_0195.nii.gz'), '-o', '/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/vol2/jsons/NKI-d23231-00-0218_20100107_kalina99_0195_phase.json']' returned non-zero exit status 1.
          # Error processing /mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20141212_kalina99_0205.nii.gz: Command '['totalseg_get_phase', '-i', np.str_('/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20141212_kalina99_0205.nii.gz'), '-o', '/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/vol2/jsons/NKI-d23231-00-0218_20141212_kalina99_0205_phase.json']' returned non-zero exit status 1.

,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,file
0,62.32,portal_venous,1.0,59.75,65.18,2.0337,NKI-d23231-00-0510_20180213_kalina99_3504.nii.gz
1,78.85,portal_venous,1.0,75.80,81.02,2.1212,NKI-d23231-00-0510_20180213_kalina99_3505.nii.gz
2,62.80,portal_venous,1.0,60.64,65.12,1.6836,NKI-d23231-00-0510_20180516_kalina99_3506.nii.gz
3,75.56,portal_venous,1.0,74.42,76.31,0.7562,NKI-d23231-00-0510_20180516_kalina99_3507.nii.gz
4,79.19,portal_venous,1.0,78.23,80.66,0.9207,NKI-d23231-00-0510_20180924_kalina99_3508.nii.gz
...,...,...,...,...,...,...,...
8725,51.08,arterial_late,0.7,47.71,54.20,2.6832,NKI-d23231-00-0155_20041209_kalina99_0344.nii.gz
8726,98.72,portal_venous,0.7,83.66,110.93,9.1340,NKI-d23231-00-0155_20050915_kalina99_0345.nii.gz
8727,65.10,portal_venous,1.0,64.18,65.72,0.5152,NKI-d23231-00-0155_20070712_kalina99_0351.nii.gz
8728,0.14,native,1.0,-0.77,1.10,0.7212,NKI-d23231-00-0155_20071112_kalina99_0353.nii.gz
8729,0.40,native,1.0,-0.47,2.11,0.9237,NKI-d23231-00-0155_20080219_kalina99_0355.nii.gz

### Merge

In [4]:
data = pd.read_csv("/projects/net_contrast_classification/contrast_phase/data/cleaned_data_1.csv")
merged_data = pd.merge(data, ts_data, left_on=["MatchKey"], right_on=["file"], how = 'left', suffixes=('', '_ts'))
merged_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8734 entries, 0 to 8733
Data columns (total 56 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   NiiFile                             8734 non-null   str
 1   SegNiiFile                          8734 non-null   str
 2   Original File                       8734 non-null   str
 3   Destination Folder                  8734 non-null   str
 4   New File                            8734 non-null   str
 5   SubjectKeyRadiology                 8734 non-null   str
 6   ExamDate                            8734 non-null   str
 7   file                                8734 non-null   str
 8   is_liver_imaged                     8573 non-null   str
 9   contrast                            8734 non-null   str
 10  phase_timing                        8734 non-null   str
 11  is_lesionfree                       8734 non-null   str
 12  ai_segmentation_quality             4490 non-null   float64
 13  manual_segmentation_confidence      4490 non-null   float64
 14  adjustment_segmentation_difficulty  4490 non-null   float64
 15  high_signal_to_noise                6637 non-null   object
 16  metal_artifacts                     6637 non-null   object
 17  patient_motion                      6637 non-null   object
 18  other                               512 non-null    str
 19  comment                             664 non-null    str
 20  time-stamp                          8734 non-null   float64
 21  Modality                            8734 non-null   str
 22  ImagingFrequency                    8734 non-null   int64
 23  Manufacturer                        8734 non-null   str
 24  ManufacturersModelName              8734 non-null   str
 25  DeviceSerialNumber                  8338 non-null   float64
 26  PatientPosition                     8734 non-null   str
 27  SoftwareVersions                    8734 non-null   str
 28  SeriesDescription                   8734 non-null   str
 29  ProtocolName                        8734 non-null   str
 30  ScanOptions                         4152 non-null   str
 31  ImageType                           8734 non-null   str
 32  SeriesNumber                        8734 non-null   int64
 33  AcquisitionTime                     8734 non-null   str
 34  AcquisitionNumber                   8387 non-null   float64
 35  ConvolutionKernel                   8734 non-null   str
 36  ExposureTime                        8410 non-null   float64
 37  XRayTubeCurrent                     8733 non-null   float64
 38  XRayExposure                        8733 non-null   float64
 39  ImageOrientationPatientDICOM        8734 non-null   str
 40  ConversionSoftware                  8734 non-null   str
 41  ConversionSoftwareVersion           8734 non-null   str
 42  BodyPartExamined                    8625 non-null   str
 43  RawImage                            186 non-null    object
 44  SliceThickness                      8689 non-null   float64
 45  AcquisitionTime_sec                 8734 non-null   float64
 46  DICOM_phase                         4905 non-null   str
 47  MatchKey                            8734 non-null   str
 48  exist_on_server                     5447 non-null   str
 49  pi_time                             8730 non-null   float64
 50  phase                               8730 non-null   str
 51  probability                         8730 non-null   float64
 52  pi_time_min                         8730 non-null   float64
 53  pi_time_max                         8730 non-null   float64
 54  stddev                              8730 non-null   float64
 55  file_ts                             8730 non-null   str
dtypes: float64(16), int64(2), object(4), str(34)
memory usage: 9.5+ MB

In [5]:
merged_data[merged_data.file_ts.isna() & merged_data.MatchKey.notna()
            ][["SubjectKeyRadiology", 'ExamDate', 'Destination Folder',
               'file',  "MatchKey", "file", "file_ts", 'exist_on_server']]

,SubjectKeyRadiology,ExamDate,Destination Folder,file,MatchKey,file,file_ts,exist_on_server
1357,NKI-d23231-00-0082,2019-08-23,DICOM-batch1-kalina99,NET_0566_0000.nii.gz,NKI-d23231-00-0082_20190823_kalina99_0566.nii.gz,NET_0566_0000.nii.gz,NaN,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
1475,NKI-d23231-00-0169,2018-05-02,DICOM-batch2-giovanni01,NET_0053_0000.nii.gz,NKI-d23231-00-0169_20180502_giovanni01_0053.ni...,NET_0053_0000.nii.gz,NaN,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
3274,NKI-d23231-00-0218,2010-01-07,DICOM-batch3-kalina99,NET_0195_0000.nii.gz,NKI-d23231-00-0218_20100107_kalina99_0195.nii.gz,NET_0195_0000.nii.gz,NaN,NaN
3283,NKI-d23231-00-0218,2014-12-12,DICOM-batch3-kalina99,NET_0205_0000.nii.gz,NKI-d23231-00-0218_20141212_kalina99_0205.nii.gz,NET_0205_0000.nii.gz,NaN,NaN

In [6]:
print("True contrast labels:\n", merged_data["contrast"].value_counts())
print("\n")
print("True timing labels:\n",merged_data["phase_timing"].value_counts())
print('\n')
print("TS labels:\n",merged_data["phase"].value_counts())

True contrast labels:
 contrast
Portal          3708
Arterial        2488
Non-contrast    2119
0                419
Name: count, dtype: int64


True timing labels:
 phase_timing
Just Right      5110
Non-contrast    2119
Too Early        916
0.0              416
Too Late         173
Name: count, dtype: int64


TS labels:
 phase
portal_venous     4763
native            2070
arterial_late     1862
arterial_early      35
Name: count, dtype: int64

In [7]:
merged_data.phase.info()

<class 'pandas.Series'>
RangeIndex: 8734 entries, 0 to 8733
Series name: phase
Non-Null Count  Dtype
--------------  -----
8730 non-null   str
dtypes: str(1)
memory usage: 166.1 KB

In [8]:
merged_data["TS_contrast"] = merged_data["phase"].str.split("_").str[0].str.capitalize()
merged_data.loc[merged_data["phase"].str.contains("native", na=False), "TS_contrast"] = "Non-contrast"

# merged_data["TS_timing"] = merged_data["phase"].apply(lambda x: x.split("_")[1].capitalize() if "_" in x else "Non-contrast")
# merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Just Right" if x == 'Venous' else x)
# merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Too Early" if x == 'Early' else x)
# merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Too Late" if x == 'Late' else x)


print('After renaming:')
print("True labels:\n", merged_data["contrast"].value_counts())
print("\n")
print("TS labels:\n",merged_data["TS_contrast"].value_counts()) # Early AP and Late AP from TS are merged in AP

After renaming:
True labels:
 contrast
Portal          3708
Arterial        2488
Non-contrast    2119
0                419
Name: count, dtype: int64


TS labels:
 TS_contrast
Portal          4763
Non-contrast    2070
Arterial        1897
Name: count, dtype: int64

In [9]:
merged_data.TS_contrast.info()

<class 'pandas.Series'>
RangeIndex: 8734 entries, 0 to 8733
Series name: TS_contrast
Non-Null Count  Dtype
--------------  -----
8730 non-null   object
dtypes: object(1)
memory usage: 68.4+ KB

In [ ]:
merged_data.to_csv("/projects/net_contrast_classification/contrast_phase/TS/TS_results.csv", index = False)

### Ground truth inconsistencies

In [34]:
diff_dicom = pd.read_csv("/projects/net_contrast_classification/contrast_phase/diff_dicom.csv")
diff_dicom[["NiiFile", "ProtocolName", "contrast", "phase_timing", "DICOM_phase"]]

,NiiFile,ProtocolName,contrast,phase_timing,DICOM_phase
0,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,PORTAAL 3MM.,Late Phase,Just Right,Portal
1,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,NaN,NaN,Portal
2,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 Bv38 2 iMAR,NaN,NaN,Arterial
3,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 2mm,Arterial,Too Late,Portal
4,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,axiaal 3 mm arterieel,Portal,Just Right,Arterial
5,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,Arterial
6,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Nier A 1.5 B25f,NaN,NaN,Arterial
7,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Nier V 1.5 B25f,NaN,NaN,Portal
8,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Uitscheiding 1.5 B25f,Late Phase,Too Late,Excretory
9,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Laat Veneus 3.0 B30f,Portal,Just Right,Late venous
10,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Portal,Just Right,Arterial
11,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 I26f 2,Portal,Too Early,Arterial
12,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,Arterial
13,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Too Early,Arterial
14,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Portal,Too Early,Arterial
15,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Lever 5 min. 1.5 B25f,Portal,Just Right,Late Phase
16,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Delayed Phase 3.0 B25f,Portal,Just Right,Late Phase
17,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,NaN,NaN,Portal
18,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Arterial Phase 3.0 B31s,NaN,NaN,Arterial
19,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,Arterial
20,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Portal,Just Right,Arterial
21,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ARTERIEEL,NaN,NaN,Arterial
22,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,NaN,NaN,Portal
23,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,LATE FASE,Portal,Just Right,Late Phase
24,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 I26f 2,Portal,Just Right,Arterial
25,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABD PV Body 1.0 CE ABD PV,Arterial,Just Right,Portal
26,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Laat Art. 2.0 B30f,Portal,Too Early,Arterial
27,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC02,Portal,Just Right,Arterial
28,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,Arterial,Too Late,Portal
29,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Lever 5 min. 1.5 B25f,Portal,Too Late,Late Phase
30,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Portal,Just Right,Arterial
31,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,Arterial
32,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,Arterial,Too Late,Portal
33,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd-Veneus 3.0 B40f,Arterial,Just Right,Portal
34,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,tra 3mm ls,NaN,NaN,Arterial
35,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Portal,Just Right,Arterial
36,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Arterieel 3.0 B30f,Portal,Just Right,Arterial
37,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,NaN,NaN,Arterial
38,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,LEVER A 1.0 FC03,Portal,Just Right,Arterial
39,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,Arterial
40,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Arterieel 3.0 B30f,Portal,Just Right,Arterial
41,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd art 2.0 MIP cor Zoom,NaN,NaN,Arterial
42,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd art 2.0 MPR ax Zoom,NaN,NaN,Arterial
43,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd veneus 2.0 MPR ax Zoom,NaN,NaN,Portal
44,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Portal,Just Right,Arterial
45,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,Arterial
46,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,Arterial
47,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Bovenbuik A20 3.0 I30f 3,Arterial,Too Early,Portal
48,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Uitscheiding 1.0 I26f 2,Portal,Too Late,Excretory
49,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Ven. fase 3.0 B31f,Arterial,Just Right,Portal
50,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,HALF 75% 1.27s Cardiac 3.000 CE Axial MPR 75% ...,NaN,NaN,Arterial
51,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,HALF 75% 1.27s Cardiac 3.000 CE Coronal MPR 75...,NaN,NaN,Arterial
52,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,HALF 75% 1.30s Cardiac 3.000 CE Axial MPR 75% ...,NaN,NaN,Arterial
53,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 Bv38 2 iMAR,NaN,NaN,Arterial
54,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 I26f 2,Portal,Just Right,Arterial
55,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Ven. fase 3.0 B31f,Arterial,Just Right,Portal

In [36]:
merged_data.contrast.value_counts()

contrast
Portal          3708
Arterial        2488
Non-contrast    2119
0                419
Name: count, dtype: int64

In [36]:
print("Entries where the contrast label != DICOM contrast label differ and DICOM labels are non-null:", len(merged_data[(merged_data["DICOM_phase"] != merged_data["contrast"]) & (merged_data["DICOM_phase"].notna())]))
merged_data[(merged_data["DICOM_phase"] != merged_data["contrast"]) & (merged_data["DICOM_phase"].notna())
            ][["NiiFile", "ProtocolName", "contrast", "phase_timing", "phase", "DICOM_phase"]].head(10)

Entries where the contrast label != DICOM contrast label differ and DICOM labels are non-null: 54

,NiiFile,ProtocolName,contrast,phase_timing,phase,DICOM_phase
199,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,Non-contrast,NaN,native,Portal
264,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 Bv38 2 iMAR,Non-contrast,NaN,native,Arterial
292,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 2mm,Arterial,Too Late,portal_venous,Portal
394,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,axiaal 3 mm arterieel,Portal,Just Right,portal_venous,Arterial
526,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Portal,Just Right,portal_venous,Arterial
629,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Nier A 1.5 B25f,Non-contrast,NaN,arterial_late,Arterial
630,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Nier V 1.5 B25f,Non-contrast,NaN,portal_venous,Portal
779,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Laat Veneus 3.0 B30f,Portal,Just Right,portal_venous,Late venous
858,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Portal,Just Right,portal_venous,Arterial
1036,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 I26f 2,Portal,Too Early,arterial_late,Arterial

In [37]:
merged_data[(merged_data["DICOM_phase"] == merged_data["TS_contrast"])
             & (merged_data["contrast"] == merged_data["TS_contrast"])
            ][["NiiFile", "ProtocolName", "contrast", "phase_timing", "phase", "DICOM_phase"]]

,NiiFile,ProtocolName,contrast,phase_timing,phase,DICOM_phase
3,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,Portal,Just Right,portal_venous,Portal
4,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,Portal,Just Right,portal_venous,Portal
5,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,ABDOMEN A 1.0 FC01,Arterial,Just Right,arterial_late,Arterial
6,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 3.0 B31f,Arterial,Too Early,arterial_late,Arterial
10,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,OMC PANCREAS VEN,Portal,Just Right,portal_venous,Portal
...,...,...,...,...,...,...
5549,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,THORABD PV Body 1.0 CE THORABD PV,Portal,Just Right,portal_venous,Portal
5550,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Bobuik art 1.0 I40f 2,Arterial,Too Early,arterial_late,Arterial
5551,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen A 1.5 B25f,Arterial,Just Right,arterial_late,Arterial
5552,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abdomen V 1.5 B25f,Portal,Just Right,portal_venous,Portal
5553,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,Abd laat-art 1.0 Bv38 2,Arterial,Just Right,arterial_late,Arterial

## Arterial vs. Portal vs. NC

In [37]:
merged_data.head(5)

,NiiFile,SegNiiFile,Original File,Destination Folder,New File,SubjectKeyRadiology,ExamDate,file,is_liver_imaged,contrast,...,MatchKey,exist_on_server,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,file_ts,TS_contrast
0,Z:\_archived\DICOM-batch1-kalina01\NET_0000_00...,Z:\_archived\DICOM-batch1-kalina01\NET_0000_00...,../DICOM-batch1\NKI-d23231-00-0063\20120416 CT...,DICOM-batch1-kalina01,NET_0000_0000.nii.gz,NKI-d23231-00-0063,2012-04-16,NET_0000_0000.nii.gz,Partially,Arterial,...,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,62.02,portal_venous,1.0,56.91,66.18,3.0706,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz,Portal
1,Z:\_archived\DICOM-batch1-kalina01\NET_0001_00...,Z:\_archived\DICOM-batch1-kalina01\NET_0001_00...,../DICOM-batch1\NKI-d23231-00-0070\20150821 CT...,DICOM-batch1-kalina01,NET_0001_0000.nii.gz,NKI-d23231-00-0070,2015-08-21,NET_0001_0000.nii.gz,Yes,Non-contrast,...,NKI-d23231-00-0070_20150821_kalina01_0001.nii.gz,NaN,-0.23,native,1.0,-0.83,0.21,0.3632,NKI-d23231-00-0070_20150821_kalina01_0001.nii.gz,Non-contrast
2,Z:\_archived\DICOM-batch1-kalina01\NET_0002_00...,Z:\_archived\DICOM-batch1-kalina01\NET_0002_00...,../DICOM-batch1\NKI-d23231-00-0036\20140218 CT...,DICOM-batch1-kalina01,NET_0002_0000.nii.gz,NKI-d23231-00-0036,2014-02-18,NET_0002_0000.nii.gz,Yes,Portal,...,NKI-d23231-00-0036_20140218_kalina01_0002.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,78.87,portal_venous,1.0,76.97,80.38,1.1980,NKI-d23231-00-0036_20140218_kalina01_0002.nii.gz,Portal
3,Z:\_archived\DICOM-batch1-kalina01\NET_0003_00...,Z:\_archived\DICOM-batch1-kalina01\NET_0003_00...,../DICOM-batch1\NKI-d23231-00-0071\20130924 CT...,DICOM-batch1-kalina01,NET_0003_0000.nii.gz,NKI-d23231-00-0071,2013-09-24,NET_0003_0000.nii.gz,Yes,Arterial,...,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,69.99,portal_venous,1.0,67.83,72.74,1.7276,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz,Portal
4,Z:\_archived\DICOM-batch1-kalina01\NET_0004_00...,Z:\_archived\DICOM-batch1-kalina01\NET_0004_00...,../DICOM-batch1\NKI-d23231-00-0077\20141222 CT...,DICOM-batch1-kalina01,NET_0004_0000.nii.gz,NKI-d23231-00-0077,2014-12-22,NET_0004_0000.nii.gz,Yes,Portal,...,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,74.84,portal_venous,1.0,66.55,82.59,5.8700,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz,Portal

In [53]:
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

test_data = merged_data[(merged_data.contrast != '0') & (merged_data.TS_contrast.notna())]

le = LabelEncoder()
y_true = le.fit_transform(test_data["contrast"])
y_pred = le.fit_transform(test_data['TS_contrast'])

print('Contrast classification accuracy:', round(accuracy_score(y_true, y_pred),3))
print("Classification report:\n", classification_report(y_true, y_pred, target_names=le.classes_))

Contrast classification accuracy: 0.896
Classification report:
               precision    recall  f1-score   support

    Arterial       0.97      0.69      0.81      2488
Non-contrast       1.00      0.97      0.98      2118
      Portal       0.82      0.99      0.90      3706

    accuracy                           0.90      8312
   macro avg       0.93      0.88      0.90      8312
weighted avg       0.91      0.90      0.89      8312

In [54]:
misclassified = test_data[
    test_data['contrast'] != test_data['TS_contrast']
]
print('Number of misclassifications:', len(misclassified))
print("Confusion matrix:")
pd.crosstab(
    test_data['contrast'],
    test_data['TS_contrast'],
    margins=True
)

Number of misclassifications: 861
Confusion matrix:

TS_contrast   Arterial  Non-contrast  Portal   All
contrast
Arterial          1712             0     776  2488
Non-contrast        23          2057      38  2118
Portal              21             3    3682  3706
All               1756          2060    4496  8312

In [ ]:
# 25 entries where DICOM contrast = TS contrast but radiologists put different label

misclass_correct_dicom = misclassified[
                (misclassified['DICOM_phase'] == misclassified['TS_contrast']) & 
                (test_data['DICOM_phase'].notna())
                ][['file', 'contrast','ProtocolName', 'DICOM_phase', 'TS_contrast']]
print(f'TS predicted the correct DICOM label for {len(misclass_correct_dicom)}/{len(misclassified)} entries.')

misclass_correct_dicom

TS predicted the correct DICOM label for 25/861 entries.

/tmp/ipykernel_2381800/3330034611.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  misclass_correct_dicom = misclassified[

,file,contrast,ProtocolName,DICOM_phase,TS_contrast
498,NET_0043_0000.nii.gz,Arterial,Abdomen V 2mm,Portal,Portal
615,NET_0059_0000.nii.gz,Non-contrast,Abdomen A 1.5 B25f,Arterial,Arterial
1523,NET_0103_0000.nii.gz,Non-contrast,Abdomen art 1.5 B30f,Arterial,Arterial
1596,NET_0179_0000.nii.gz,Portal,Abd laat-art 1.0 I26f 2,Arterial,Arterial
1648,NET_0231_0000.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
1968,NET_0056_0000.nii.gz,Portal,Lever -C 1.5 B25f,Non-contrast,Non-contrast
2699,NET_0124_0000.nii.gz,Portal,ABDOMEN A 1.0 FC01,Arterial,Arterial
3066,NET_0511_0000.nii.gz,Arterial,ABD PV Body 1.0 CE ABD PV,Portal,Portal
3176,NET_0096_0000.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
3370,NET_0292_0000.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
4391,NET_1333_0000.nii.gz,Portal,ABDOMEN A 1.0 FC01,Arterial,Arterial
4446,NET_1389_0000.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
4734,NET_1679_0000.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
4788,NET_1736_0000.nii.gz,Non-contrast,ABDOMEN A 1.0 FC02,Arterial,Arterial
5269,NET_2225_0000.nii.gz,Arterial,Abd-Veneus 3.0 B40f,Portal,Portal
6013,NET_2985_0000.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
6420,NET_3398_0000.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
6487,NET_3474_0000.nii.gz,Non-contrast,Lever A 2mm,Arterial,Arterial
6531,NET_3525_0000.nii.gz,Portal,Arterieel 3.0 B30f,Arterial,Arterial
7289,NET_4330_0000.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
7461,NET_4521_0000.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
7570,NET_4635_0000.nii.gz,Portal,LEVER -C 1.0 FC07,Non-contrast,Non-contrast
8305,NET_5394_0000.nii.gz,Arterial,Ven. fase 3.0 B31f,Portal,Portal
8308,NET_5397_0000.nii.gz,Arterial,Ven. fase 3.0 B31f,Portal,Portal
8516,NET_5613_0000.nii.gz,Arterial,Ven. fase 3.0 B31f,Portal,Portal

In [56]:
misclass_dicom = misclassified[
    (misclassified['TS_contrast'] != misclassified['DICOM_phase']) |
    (misclassified['DICOM_phase'].isna())
][['file', 'contrast','ProtocolName', 'DICOM_phase', 'TS_contrast']]

print('Number of entries where both DICOM and radiologists\' contrast != TS contrast:', len(misclass_dicom))
misclass_dicom.tail(5)

Number of entries where both DICOM and radiologists' contrast != TS contrast: 836

,file,contrast,ProtocolName,DICOM_phase,TS_contrast
8677,NET_5775_0000.nii.gz,Arterial,Abd laat-art 1.0 Bv38 2,Arterial,Portal
8703,NET_5801_0000.nii.gz,Arterial,Abd laat-art 1.0 Bv38 2,Arterial,Portal
8713,NET_5811_0000.nii.gz,Arterial,Abdomen A 1.5 B25f,Arterial,Portal
8717,NET_5815_0000.nii.gz,Arterial,Abdomen A 1.5 B25f,Arterial,Portal
8732,NET_5830_0000.nii.gz,Arterial,Abd laat-art 1.0 Bv38 2,Arterial,Portal

In [57]:
misclassified.is_liver_imaged.value_counts()

is_liver_imaged
Yes          807
Partially     37
0              1
Name: count, dtype: int64

In [58]:
misclassified = misclassified[misclassified.is_liver_imaged != '0']
misclassified.is_liver_imaged.value_counts()

is_liver_imaged
Yes          807
Partially     37
Name: count, dtype: int64

### Visualizing the missclassifications

In [27]:
from monai.transforms import LoadImage, EnsureChannelFirst


folder_path = "/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET"


def data_load(folder_dir, data, group_col = 'contrast', num = 3, channel_first = True, load = True):
    samples = (data.groupby(group_col)
           .apply(lambda x: x.sample(n=min(num, len(x)), random_state=42))
           .reset_index()
                   )
    
    images = [] 
    
    if load == True:  
        loader = LoadImage(image_only=True)
        files = list(samples['file'])
        phases = list(samples['contrast'])
        for file in files:
            file_dir = os.path.join(folder_dir, PureWindowsPath(file).name)
            ct = loader(file_dir)
            if channel_first:
                ct = EnsureChannelFirst()(ct)

            ct = ct.numpy()
            images.append(ct)

    return samples, phases, images


samples, phases, misclass_images = data_load(folder_path, misclassified)

In [28]:
samples

,contrast,level_1,SubjectKeyRadiology,ExamDate,SegmentationBatch,NiiFile,SegNiiFile,file,is_liver_imaged,phase_timing,...,slice_thickness,DICOM_phase,file0,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,TS_contrast
0,Arterial,5360,NKI-d23231-00-0865,2022-06-23,kalina99_5717,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0865_20220623_kalina99_5717.nii.gz,Yes,Just Right,...,1.0,Arterial,NET_5717_0000.nii.gz,78.88,portal_venous,1.0,72.90,82.48,4.1572,Portal
1,Arterial,2181,NKI-d23231-00-0227,2013-02-12,kalina99_0318,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0227_20130212_kalina99_0318.nii.gz,Yes,Too Early,...,1.0,Arterial,NET_0318_0000.nii.gz,64.20,portal_venous,1.0,59.08,67.98,3.1636,Portal
2,Arterial,5034,NKI-d23231-00-0795,2019-01-31,kalina99_5279,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0795_20190131_kalina99_5279.nii.gz,Yes,Just Right,...,1.5,Arterial,NET_5279_0000.nii.gz,64.66,portal_venous,1.0,60.42,69.63,3.5250,Portal
3,Non-contrast,1482,NKI-d23231-00-0170,2006-04-05,kalina99_0444,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0170_20060405_kalina99_0444.nii.gz,Yes,Just Right,...,1.5,NaN,NET_0444_0000.nii.gz,82.13,portal_venous,1.0,77.66,87.60,3.8453,Portal
4,Non-contrast,1596,NKI-d23231-00-0193,2016-10-12,kalina99_0660,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0193_20161012_kalina99_0660.nii.gz,Yes,Too Early,...,1.0,NaN,NET_0660_0000.nii.gz,77.88,portal_venous,1.0,75.51,80.96,1.7601,Portal
5,Non-contrast,4160,NKI-d23231-00-0532,2015-08-18,kalina99_3669,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0532_20150818_kalina99_3669.nii.gz,Yes,Just Right,...,1.5,Portal,NET_3669_0000.nii.gz,81.06,portal_venous,1.0,78.78,83.38,1.7551,Portal
6,Portal,243,NKI-d23231-00-0024,2021-04-23,kalina08_0039,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0024_20210423_kalina08_0039.nii.gz,Yes,Just Right,...,1.0,NaN,NET_0039_0000.nii.gz,56.71,arterial_late,0.7,50.85,60.37,3.3814,Arterial
7,Portal,4551,NKI-d23231-00-0653,2020-10-14,kalina99_4513,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0653_20201014_kalina99_4513.nii.gz,Yes,Just Right,...,1.0,NaN,NET_4513_0000.nii.gz,59.04,arterial_late,0.7,56.94,60.34,1.2221,Arterial
8,Portal,4487,NKI-d23231-00-0615,2017-10-21,kalina99_4355,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0615_20171021_kalina99_4355.nii.gz,Yes,Just Right,...,1.0,NaN,NET_4355_0000.nii.gz,57.09,arterial_late,0.7,51.56,60.78,3.4093,Arterial

In [29]:
misclass_images[4].shape

(1, 512, 512, 145)

In [ ]:
def show_slices_per_class(images, center=50, width=300):

    def window_ct(img, center, width):
        low = center - width/2
        high = center + width/2
        return img.clip(low, high)


    class_ranges = {
        "Arterial": range(0, 3),
        "Non-contrast": range(3, 6),
        "Portal": range(6, 9)
    }

    for cls_name, indices in class_ranges.items():

        if cls_name == 'Portal':
            z = 50
        else:
            z = int(np.mean([images[i].shape[3] for i in indices]))- 30

        plt.figure(figsize=(15,5))
        for j, i in enumerate(indices):
            img = images[i][0, :, :, z]
            plt.subplot(1, 3, j+1)
            plt.imshow(np.rot90(window_ct(img, center, width),k=1), cmap="gray")
            plt.title(f"{cls_name} image {i}, slice {z}")
            plt.axis("off")
        plt.show()

show_slices_per_class(misclass_images)

SyntaxError: invalid character '§' (U+00A7) (2721995884.py, line 20)

## Phase + Timing Classification Results

In [ ]:
# merged_data.loc[merged_data["contrast"] == "Portal","phase_timing"] = "Just Right"

# merged_data["phase_timing_combined"] = (merged_data["contrast"].str.cat(merged_data["phase_timing"], sep=" "))
# merged_data["TS_phase_timing_combined"] = (merged_data["TS_contrast"].str.cat(merged_data["TS_timing"], sep=" "))

# print(merged_data["phase_timing_combined"].value_counts())
# print("\n")
# print(merged_data["TS_phase_timing_combined"].value_counts())


# contrast_correct = merged_data[merged_data["contrast"] == merged_data["TS_contrast"]].copy()

# y_true = le.fit_transform(contrast_correct["phase_timing"])
# y_pred = le.fit_transform(contrast_correct['TS_timing'])

# print('Timing classification accuracy:', round(accuracy_score(y_true, y_pred),3))
# print("Classification report:\n", classification_report(y_true, y_pred, target_names=le.classes_))

# print("Confusion matrix:")
# pd.crosstab(
#     contrast_correct["phase_timing"],
#     contrast_correct['TS_timing'],
#     margins=True
# )

phase_timing_combined
Portal Just Right            3133
Arterial Just Right          1365
Arterial Too Early            661
Arterial Too Late              97
Portal Too Early               97
Portal Too Late                51
Non-contrast Non-contrast      42
Name: count, dtype: int64


TS_phase_timing_combined
Portal Just Right            3922
Arterial Too Late            1482
Non-contrast Non-contrast      30
Arterial Too Early             12
Name: count, dtype: int64

## Time Interval Estimation

### Only contrast data

In [60]:
contrast_data = test_data[test_data["contrast"] !='Non-contrast'] # ignore the NC images as they are only 42 
cols = ['SubjectKeyRadiology', 'ExamDate', 'contrast', 'phase_timing', 'TS_contrast', 'phase', 'DICOM_phase',
        'AcquisitionTime', 'AcquisitionTime_sec', 'pi_time','SliceThickness', 'ProtocolName', 'ConvolutionKernel',
        'pi_time_min', 'pi_time_max', 'stddev', 'file', 'BodyPartExamined']

contrast_data=contrast_data.sort_values(by=['SubjectKeyRadiology', 'ExamDate','AcquisitionTime'], ascending=[True, True, True]).reset_index()
contrast_data[cols]

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
0,NKI-d23231-00-0001,2006-09-20,Portal,Too Early,Portal,portal_venous,NaN,12:07:42.451000,43662.45100,85.59,1.5,Abdomen 1.5 B30f,B30f,82.12,93.46,4.2121,NET_0045_0000.nii.gz,ABDOMEN
1,NKI-d23231-00-0001,2007-06-08,Portal,Just Right,Portal,portal_venous,NaN,11:47:19.223200,42439.22320,82.55,1.5,Abdomen +C 1.5 B30f,B30f,80.15,83.99,1.3290,NET_0023_0000.nii.gz,ABDOMEN
2,NKI-d23231-00-0001,2007-08-15,Portal,Just Right,Portal,portal_venous,Arterial,11:51:28.000000,42688.00000,64.49,2.0,COR 2MM ART,B,63.78,65.62,0.6663,NET_0000_0000.nii.gz,NaN
3,NKI-d23231-00-0001,2007-08-15,Portal,Too Early,Portal,portal_venous,NaN,11:51:28.000000,42688.00000,65.44,2.0,PANCREAS 2MM.,B,62.05,67.68,1.8933,NET_0002_0000.nii.gz,PANCREAS
4,NKI-d23231-00-0001,2007-08-15,Portal,Just Right,Portal,portal_venous,Portal,11:51:53.000000,42713.00000,74.22,3.0,PORTAAL 3MM.,B,71.60,77.96,2.7185,NET_0007_0000.nii.gz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6189,NKI-d23231-00-0888,2022-04-20,Portal,Just Right,Portal,portal_venous,Portal,15:13:16.119320,54796.11932,80.39,1.5,Abdomen V 1.5 B25f,B25f,78.27,82.66,1.4937,NET_5827_0000.nii.gz,ABDOMEN
6190,NKI-d23231-00-0888,2023-04-24,Arterial,Just Right,Arterial,arterial_late,Arterial,12:05:45.561000,43545.56100,59.19,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.14,61.54,1.8509,NET_5828_0000.nii.gz,ABDOMEN
6191,NKI-d23231-00-0888,2023-04-24,Portal,Just Right,Portal,portal_venous,NaN,12:06:20.138000,43580.13800,77.28,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,74.66,78.94,1.6271,NET_5829_0000.nii.gz,ABDOMEN
6192,NKI-d23231-00-0888,2023-08-01,Arterial,Just Right,Portal,portal_venous,Arterial,11:43:20.650000,42200.65000,63.08,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,60.32,64.76,1.5287,NET_5830_0000.nii.gz,ABDOMEN
6193,NKI-d23231-00-0888,2023-08-01,Portal,Just Right,Portal,portal_venous,NaN,11:43:50.042000,42230.04200,73.31,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,72.83,73.69,0.2884,NET_5831_0000.nii.gz,ABDOMEN

In [61]:
# ASK
print('Same acquisition time, different time prediction due to reconstruction kernel')
contrast_data[cols][contrast_data.SubjectKeyRadiology == 'NKI-d23231-00-0281'].head(2)

Same acquisition time, different time prediction due to reconstruction kernel

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
2553,NKI-d23231-00-0281,2014-05-20,Portal,Just Right,Portal,portal_venous,NaN,12:31:15.181500,45075.18150,71.83,1.5,ThxAbd 1.5 B25f,B25f,69.96,74.97,1.8208,NET_0953_0000.nii.gz,CHEST
2554,NKI-d23231-00-0281,2014-05-20,Portal,Just Right,Portal,portal_venous,NaN,12:31:15.183190,45075.18319,70.51,3.0,ThxAbd 3.0 B31f,B31f,67.65,72.06,1.5080,NET_0954_0000.nii.gz,CHEST

In [62]:
# def time_to_seconds(t):
#     minutes, seconds = t.split(':')
#     return int(minutes) * 60 + float(seconds)

unique_keys = ["SubjectKeyRadiology"
               ,"ExamDate"
               ,"ConvolutionKernel"
               , 'SliceThickness'
               , 'BodyPartExamined'
                ]

# contrast_data['AcquisitionTime_sec'] = contrast_data['AcquisitionTime'].apply(time_to_seconds)

contrast_data["time_interval"] = (
    contrast_data
    .groupby(unique_keys)["AcquisitionTime_sec"]
    .diff()
    .shift(-1)
    .ffill(limit = 1)
)

contrast_data["TS_time_interval"] = (
    contrast_data
    .groupby(unique_keys)["pi_time"]
    .diff()
    .shift(-1)
    .ffill(limit = 1)
    )

In [63]:
contrast_data['TS_time_interval'] = contrast_data['TS_time_interval'].apply(lambda x: abs(x))
contrast_data['time_interval'] = contrast_data['time_interval'].apply(lambda x: abs(x))

cols.insert(9,'time_interval')
cols.insert(10, 'TS_time_interval')

contrast_data[cols][contrast_data.SubjectKeyRadiology == 'NKI-d23231-00-0281']

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
2553,NKI-d23231-00-0281,2014-05-20,Portal,Just Right,Portal,portal_venous,NaN,12:31:15.181500,45075.18150,NaN,NaN,71.83,1.5,ThxAbd 1.5 B25f,B25f,69.96,74.97,1.8208,NET_0953_0000.nii.gz,CHEST
2554,NKI-d23231-00-0281,2014-05-20,Portal,Just Right,Portal,portal_venous,NaN,12:31:15.183190,45075.18319,NaN,NaN,70.51,3.0,ThxAbd 3.0 B31f,B31f,67.65,72.06,1.5080,NET_0954_0000.nii.gz,CHEST
2555,NKI-d23231-00-0281,2014-07-29,Arterial,Just Right,Arterial,arterial_late,Arterial,14:05:34.050000,50734.05000,24.20000,31.18,43.25,1.0,ABDOMEN A 1.0 FC01,FC01,39.70,47.20,2.4776,NET_0956_0000.nii.gz,ABDOMEN
2556,NKI-d23231-00-0281,2014-07-29,Portal,Just Right,Portal,portal_venous,NaN,14:05:58.250000,50758.25000,24.20000,31.18,74.43,1.0,ABDOMEN + C 1.0 FC01,FC01,72.82,75.83,0.9713,NET_0955_0000.nii.gz,ABDOMEN
2557,NKI-d23231-00-0281,2014-10-27,Arterial,Just Right,Arterial,arterial_late,Arterial,09:59:52.800000,35992.80000,30.20000,30.57,43.70,1.0,ABDOMEN A 1.0 FC01,FC01,42.06,46.00,1.4908,NET_0958_0000.nii.gz,ABDOMEN
2558,NKI-d23231-00-0281,2014-10-27,Portal,Just Right,Portal,portal_venous,NaN,10:00:23.000000,36023.00000,30.20000,30.57,74.27,1.0,ABDOMEN + C 1.0 FC01,FC01,72.79,75.69,1.0710,NET_0957_0000.nii.gz,ABDOMEN
2559,NKI-d23231-00-0281,2015-01-26,Arterial,Just Right,Arterial,arterial_late,Arterial,09:55:11.550000,35711.55000,27.95000,18.66,56.66,1.0,ABDOMEN A 1.0 FC01,FC01,52.94,61.28,3.0092,NET_0960_0000.nii.gz,ABDOMEN
2560,NKI-d23231-00-0281,2015-01-26,Portal,Just Right,Portal,portal_venous,NaN,09:55:39.500000,35739.50000,27.95000,18.66,75.32,1.0,ABDOMEN + C 1.0 FC01,FC01,70.36,78.17,2.7471,NET_0959_0000.nii.gz,ABDOMEN
2561,NKI-d23231-00-0281,2015-08-19,Arterial,Just Right,Arterial,arterial_late,Arterial,16:00:24.550000,57624.55000,30.20000,33.08,44.46,1.0,ABDOMEN A 1.0 FC01,FC01,42.30,49.33,2.5411,NET_0962_0000.nii.gz,ABDOMEN
2562,NKI-d23231-00-0281,2015-08-19,Portal,Just Right,Portal,portal_venous,NaN,16:00:54.750000,57654.75000,30.20000,33.08,77.54,1.0,ABDOMEN + C 1.0 FC01,FC01,73.25,80.34,2.7655,NET_0961_0000.nii.gz,ABDOMEN
2563,NKI-d23231-00-0281,2017-10-10,Arterial,Just Right,Arterial,arterial_early,NaN,13:13:36.350000,47616.35000,NaN,NaN,27.62,1.0,Body 1.0 CE Vol.,FC01,25.69,29.37,1.2803,NET_0963_0000.nii.gz,ABDOMEN
2564,NKI-d23231-00-0281,2018-03-14,Arterial,Too Early,Arterial,arterial_late,Arterial,12:25:13.509590,44713.50959,57.92200,42.46,35.16,1.5,Abdomen A 1.5 B25f,B25f,31.62,37.67,2.1180,NET_0966_0000.nii.gz,ABDOMEN
2565,NKI-d23231-00-0281,2018-03-14,Portal,Just Right,Portal,portal_venous,Portal,12:26:11.431590,44771.43159,57.92200,42.46,77.62,1.5,Abdomen V 1.5 B25f,B25f,76.40,78.73,0.8546,NET_0967_0000.nii.gz,ABDOMEN
2566,NKI-d23231-00-0281,2018-03-21,Arterial,Too Early,Arterial,arterial_late,Arterial,10:24:19.823290,37459.82329,58.09290,43.47,33.97,1.5,Abdomen A 1.5 B25f,B25f,29.78,40.29,3.8907,NET_0970_0000.nii.gz,ABDOMEN
2567,NKI-d23231-00-0281,2018-03-21,Portal,Just Right,Portal,portal_venous,Portal,10:25:17.916190,37517.91619,58.09290,43.47,77.44,1.5,Abdomen V 1.5 B25f,B25f,74.21,79.71,1.8885,NET_0971_0000.nii.gz,ABDOMEN
2568,NKI-d23231-00-0281,2018-03-23,Arterial,Too Early,Arterial,arterial_late,Arterial,15:53:22.182110,57202.18211,57.64088,42.86,33.51,1.5,Abdomen A 1.5 B25f,B25f,28.43,37.80,3.4456,NET_0974_0000.nii.gz,ABDOMEN
2569,NKI-d23231-00-0281,2018-03-23,Portal,Just Right,Portal,portal_venous,Portal,15:54:19.822990,57259.82299,57.64088,42.86,76.37,1.5,Abdomen V 1.5 B25f,B25f,72.76,82.95,3.7314,NET_0975_0000.nii.gz,ABDOMEN
2570,NKI-d23231-00-0281,2018-05-01,Portal,Just Right,Portal,portal_venous,NaN,11:10:53.550000,40253.55000,NaN,NaN,76.99,1.0,Body 1.0 CE Vol.,FC01,73.95,79.12,1.7970,NET_0978_0000.nii.gz,ABDOMEN
2571,NKI-d23231-00-0281,2018-08-29,Portal,Just Right,Portal,portal_venous,NaN,11:16:33.100000,40593.10000,NaN,NaN,73.38,1.0,Body 1.0 CE Vol.,FC01,70.77,75.04,1.5682,NET_0979_0000.nii.gz,ABDOMEN
2572,NKI-d23231-00-0281,2019-05-17,Arterial,Too Early,Arterial,arterial_late,Arterial,09:46:59.948000,35219.94800,36.50300,37.17,31.41,1.0,Abd laat-art 1.0 I26f 2,I26f\2,28.89,32.91,1.3893,NET_0980_0000.nii.gz,ABDOMEN
2573,NKI-d23231-00-0281,2019-05-17,Arterial,Just Right,Portal,portal_venous,NaN,09:47:36.451000,35256.45100,36.50300,37.17,68.58,1.0,Abdomen 1.0 I26f 2,I26f\2,66.59,70.53,1.4057,NET_0981_0000.nii.gz,ABDOMEN
2574,NKI-d23231-00-0281,2019-11-07,Arterial,Just Right,Arterial,arterial_late,Arterial,15:21:23.540570,55283.54057,58.78263,53.70,31.53,1.5,Abdomen A 1.5 B25f,B25f,29.16,33.12,1.2972,NET_0982_0000.nii.gz,ABDOMEN
2575,NKI-d23231-00-0281,2019-11-07,Portal,Just Right,Portal,portal_venous,Portal,15:22:22.323200,55342.32320,58.78263,53.70,85.23,1.5,Abdomen V 1.5 B25f,B25f,83.18,89.18,2.1476,NET_0983_0000.nii.gz,ABDOMEN
2576,NKI-d23231-00-0281,2020-04-14,Portal,Just Right,Portal,portal_venous,NaN,17:49:45.950000,64185.95000,NaN,NaN,70.92,1.0,Body 1.0 CE Vol.,FC01,69.07,72.23,1.0998,NET_0984_0000.nii.gz,ABDOMEN

In [64]:
# ASK - more than 3 entries per exam (due to different protocols or incorrect NC labels => different ordering => different intervals)
multi_phase = (
    contrast_data
    .groupby(unique_keys)
    .filter(lambda x: len(x) > 2)
)

multi_phase[cols].sort_values(
        by=['SubjectKeyRadiology', 'ExamDate', 'AcquisitionTime'])

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
58,NKI-d23231-00-0007,2022-02-21,Portal,Just Right,Portal,portal_venous,Portal,14:29:26.571000,52166.57100,0.00000,0.22,68.42,3.0,AbdVeneus 3.0 MPR sag,I40f\2,67.34,69.35,0.8846,NET_0014_0000.nii.gz,ABDOMEN
59,NKI-d23231-00-0007,2022-02-21,Portal,Just Right,Portal,portal_venous,Portal,14:29:26.571000,52166.57100,0.30300,4.75,68.64,3.0,AbdVeneus 3.0 MPR cor,I40f\2,67.42,69.37,0.6925,NET_0043_0000.nii.gz,ABDOMEN
60,NKI-d23231-00-0007,2022-02-21,Portal,Just Right,Portal,portal_venous,Portal,14:29:26.874000,52166.87400,0.30300,4.75,73.39,3.0,AbdVeneus 3.0 I40f 2,I40f\2,69.97,74.99,1.8226,NET_0047_0000.nii.gz,ABDOMEN
1088,NKI-d23231-00-0109,2006-12-14,Portal,Just Right,Non-contrast,native,Non-contrast,15:10:56.432010,54656.43201,94.64575,46.52,0.09,1.5,Lever -C 1.5 B25f,B25f,-0.49,0.60,0.3965,NET_0056_0000.nii.gz,ABDOMEN
1089,NKI-d23231-00-0109,2006-12-14,Arterial,Just Right,Arterial,arterial_late,Arterial,15:12:31.077760,54751.07776,288.51576,5.30,46.61,1.5,Lever A 1.5 B25f,B25f,39.70,54.62,5.1852,NET_0057_0000.nii.gz,ABDOMEN
1090,NKI-d23231-00-0109,2006-12-14,Portal,Just Right,Arterial,arterial_late,Late Phase,15:17:19.593520,55039.59352,288.51576,5.30,51.91,1.5,Lever 5 min. 1.5 B25f,B25f,48.45,54.89,2.3487,NET_0143_0000.nii.gz,ABDOMEN
1311,NKI-d23231-00-0149,2007-03-20,Arterial,Just Right,Arterial,arterial_late,Arterial,12:56:51.365720,46611.36572,36.47408,17.45,52.44,3.0,Arterial Phase 3.0 B25f,B25f,49.95,56.62,2.3829,NET_0262_0000.nii.gz,ABDOMEN
1312,NKI-d23231-00-0149,2007-03-20,Portal,Just Right,Portal,portal_venous,Portal,12:57:27.839800,46647.83980,106.52620,10.31,69.89,3.0,Venous Phase 3.0 B25f,B25f,65.94,72.98,2.3329,NET_0087_0000.nii.gz,ABDOMEN
1313,NKI-d23231-00-0149,2007-03-20,Portal,Just Right,Portal,portal_venous,Late Phase,12:59:14.366000,46754.36600,106.52620,10.31,80.20,3.0,Delayed Phase 3.0 B25f,B25f,76.86,83.44,2.5671,NET_0263_0000.nii.gz,ABDOMEN
3818,NKI-d23231-00-0420,2014-07-04,Portal,Just Right,Portal,portal_venous,Arterial,10:19:18.642500,37158.64250,33.29699,8.46,66.69,3.0,Arterieel 3.0 B30f,B30f,65.42,67.38,0.6966,NET_2725_0000.nii.gz,ABDOMEN
3819,NKI-d23231-00-0420,2014-07-04,Portal,Just Right,Portal,portal_venous,Portal,10:19:51.939490,37191.93949,235.57852,5.44,75.15,3.0,Veneus 3.0 B30f,B30f,71.16,77.74,2.4462,NET_2727_0000.nii.gz,ABDOMEN
3820,NKI-d23231-00-0420,2014-07-04,Portal,Too Late,Portal,portal_venous,Portal,10:23:47.518010,37427.51801,235.57852,5.44,69.71,3.0,Veneus laat 3.0 B30f,B30f,66.32,73.65,2.5375,NET_2728_0000.nii.gz,ABDOMEN
3859,NKI-d23231-00-0424,2015-05-01,Arterial,Just Right,Portal,portal_venous,Arterial,11:51:56.280520,42716.28052,35.82145,13.20,62.93,3.0,Arterieel 3.0 B30f,B30f,60.98,63.98,1.0157,NET_0183_0000.nii.gz,ABDOMEN
3860,NKI-d23231-00-0424,2015-05-01,Portal,Just Right,Portal,portal_venous,Portal,11:52:32.101970,42752.10197,190.10401,9.85,76.13,3.0,Veneus 3.0 B30f,B30f,74.77,77.10,0.8490,NET_2786_0000.nii.gz,ABDOMEN
3861,NKI-d23231-00-0424,2015-05-01,Portal,Too Late,Portal,portal_venous,Portal,11:55:42.205980,42942.20598,190.10401,9.85,85.98,3.0,Veneus laat 3.0 B30f,B30f,84.83,87.78,1.0210,NET_2787_0000.nii.gz,ABDOMEN
4543,NKI-d23231-00-0535,2019-09-18,Arterial,Just Right,Arterial,arterial_late,Arterial,11:44:33.167000,42273.16700,0.00000,0.26,53.58,1.0,Abd laat-art 1.0 I26f 2 iMAR,I26f\2,47.59,59.49,4.9791,NET_3754_0000.nii.gz,ABDOMEN
4544,NKI-d23231-00-0535,2019-09-18,Arterial,Just Right,Arterial,arterial_late,Arterial,11:44:33.167000,42273.16700,37.93800,19.33,53.84,1.0,Abd laat-art 1.0 I26f 2,I26f\2,48.53,59.80,4.8582,NET_3755_0000.nii.gz,ABDOMEN
4545,NKI-d23231-00-0535,2019-09-18,Portal,Just Right,Portal,portal_venous,NaN,11:45:11.105000,42311.10500,0.00000,2.17,73.17,1.0,Abdomen 1.0 I26f 2 iMAR,I26f\2,70.52,75.75,1.8035,NET_3756_0000.nii.gz,ABDOMEN
4546,NKI-d23231-00-0535,2019-09-18,Portal,Just Right,Portal,portal_venous,NaN,11:45:11.105000,42311.10500,0.00000,2.17,71.00,1.0,Abdomen 1.0 I26f 2,I26f\2,69.38,73.31,1.3085,NET_3757_0000.nii.gz,ABDOMEN
4558,NKI-d23231-00-0535,2022-07-19,Arterial,Just Right,Arterial,arterial_late,Arterial,14:01:30.540000,50490.54000,0.00000,3.41,57.71,1.0,Abd laat-art 1.0 Bv38 2 iMAR,Bv38f\2,50.40,62.33,4.2817,NET_3769_0000.nii.gz,ABDOMEN
4559,NKI-d23231-00-0535,2022-07-19,Arterial,Just Right,Portal,portal_venous,Arterial,14:01:30.540000,50490.54000,0.00000,3.41,61.12,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.96,64.00,2.3650,NET_3770_0000.nii.gz,ABDOMEN
4561,NKI-d23231-00-0535,2022-07-19,Portal,Just Right,Portal,portal_venous,NaN,14:02:7.336000,50527.33600,36.79600,12.19,73.31,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,71.97,74.31,0.7583,NET_3772_0000.nii.gz,ABDOMEN
5649,NKI-d23231-00-0793,2017-10-03,Arterial,Just Right,Arterial,arterial_early,NaN,12:27:31.279000,44851.27900,17.49800,39.39,29.57,3.0,Art.Lever+thora 3.0 B40f,B40f,27.00,31.50,1.4892,NET_0439_0000.nii.gz,ABDOMEN
5650,NKI-d23231-00-0793,2017-10-03,Portal,Just Right,Portal,portal_venous,Portal,12:27:48.777000,44868.77700,192.55400,2.00,68.96,3.0,Abd-Veneus 3.0 B40f,B40f,67.37,72.08,1.6875,NET_5270_0000.nii.gz,ABDOMEN
5651,NKI-d23231-00-0793,2017-10-03,Portal,Too Late,Portal,portal_venous,Portal,12:31:1.331000,45061.33100,192.55400,2.00,66.96,3.0,Lever-Laat ven 3.0 B40f,B40f,65.98,68.29,0.8409,NET_5273_0000.nii.gz,ABDOMEN

In [65]:
contrast_data.time_interval.info()

<class 'pandas.Series'>
RangeIndex: 6194 entries, 0 to 6193
Series name: time_interval
Non-Null Count  Dtype
--------------  -----
3592 non-null   float64
dtypes: float64(1)
memory usage: 48.5 KB

In [66]:
contrast_data= contrast_data.dropna(subset=["time_interval"],ignore_index=True)

In [67]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error

print("MAE:", mean_absolute_error(contrast_data.time_interval,contrast_data.TS_time_interval))
print("RMSE:", root_mean_squared_error(contrast_data.time_interval,contrast_data.TS_time_interval))

MAE: 20.489092619710416
RMSE: 31.42860601992331

### Only correct classifications

In [68]:
contrast_correct = contrast_data[contrast_data["contrast"] == contrast_data["TS_contrast"]].copy()
contrast_correct = contrast_correct.sort_values(by=['SubjectKeyRadiology', 'ExamDate','AcquisitionTime'], ascending=[True, True, True]).reset_index()


contrast_correct["time_interval"] = (
    contrast_correct
    .groupby(unique_keys)["AcquisitionTime_sec"]
    .diff()
    .shift(-1)
    .ffill(limit = 1)
)

contrast_correct["TS_time_interval"] = (
    contrast_correct
    .groupby(unique_keys)["pi_time"]
    .diff()
    .shift(-1)
    .ffill(limit = 1)
    )

contrast_correct['TS_time_interval'] = contrast_correct['TS_time_interval'].apply(lambda x: abs(x))
contrast_correct['time_interval'] = contrast_correct['time_interval'].apply(lambda x: abs(x))

In [69]:
contrast_correct= contrast_correct.dropna(subset=["time_interval"],ignore_index=True)

print("MAE:", mean_absolute_error(contrast_correct.time_interval,contrast_correct.TS_time_interval))
print("RMSE:", root_mean_squared_error(contrast_correct.time_interval,contrast_correct.TS_time_interval))

MAE: 18.494873235294055
RMSE: 29.380366155446268

In [70]:
contrast_correct['error'] = abs(contrast_correct.TS_time_interval - contrast_correct.time_interval)
contrast_correct.error.describe()

count    2482.000000
mean       18.494873
std        22.833213
min         0.013100
25%         7.620600
50%        15.840000
75%        26.177690
max       441.436000
Name: error, dtype: float64

In [71]:
top_outliers = contrast_correct.sort_values('error', ascending=False).head(50)
top_outliers[cols].head(10)

# UITSCHEIDING is it delayed phase?

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
2245,NKI-d23231-00-0762,2019-12-27,Arterial,Just Right,Arterial,arterial_late,Arterial,08:34:59.409000,30899.40900,471.47600,30.04,40.94,1.0,Abd art 1.0 I26f 2,I26f\2,38.43,42.35,1.4060,NET_5028_0000.nii.gz,ABDOMEN
2246,NKI-d23231-00-0762,2019-12-27,Portal,Too Late,Portal,portal_venous,Excretory,08:42:50.885000,31370.88500,471.47600,30.04,70.98,1.0,Uitscheiding 1.0 I26f 2,I26f\2,60.01,74.74,5.5189,NET_5029_0000.nii.gz,ABDOMEN
2038,NKI-d23231-00-0540,2016-04-09,Portal,Just Right,Portal,portal_venous,Arterial,12:22:5.200000,44525.20000,429.55000,1.58,78.78,1.0,ABDOMEN A 1.0 FC01,FC01,76.17,83.23,2.5552,NET_3857_0000.nii.gz,ABDOMEN
2037,NKI-d23231-00-0540,2016-04-09,Portal,Just Right,Portal,portal_venous,NaN,12:14:55.650000,44095.65000,429.55000,1.58,80.36,1.0,ABDOMEN + C 1.0 FC01,FC01,77.25,87.62,3.7352,NET_3856_0000.nii.gz,ABDOMEN
1737,NKI-d23231-00-0420,2014-07-04,Portal,Just Right,Portal,portal_venous,Portal,10:19:51.939490,37191.93949,235.57852,5.44,75.15,3.0,Veneus 3.0 B30f,B30f,71.16,77.74,2.4462,NET_2727_0000.nii.gz,ABDOMEN
1738,NKI-d23231-00-0420,2014-07-04,Portal,Too Late,Portal,portal_venous,Portal,10:23:47.518010,37427.51801,235.57852,5.44,69.71,3.0,Veneus laat 3.0 B30f,B30f,66.32,73.65,2.5375,NET_2728_0000.nii.gz,ABDOMEN
2306,NKI-d23231-00-0793,2017-10-03,Portal,Just Right,Portal,portal_venous,Portal,12:27:48.777000,44868.77700,192.55400,2.00,68.96,3.0,Abd-Veneus 3.0 B40f,B40f,67.37,72.08,1.6875,NET_5270_0000.nii.gz,ABDOMEN
2307,NKI-d23231-00-0793,2017-10-03,Portal,Too Late,Portal,portal_venous,Portal,12:31:1.331000,45061.33100,192.55400,2.00,66.96,3.0,Lever-Laat ven 3.0 B40f,B40f,65.98,68.29,0.8409,NET_5273_0000.nii.gz,ABDOMEN
1759,NKI-d23231-00-0424,2015-05-01,Portal,Just Right,Portal,portal_venous,Portal,11:52:32.101970,42752.10197,190.10401,9.85,76.13,3.0,Veneus 3.0 B30f,B30f,74.77,77.10,0.8490,NET_2786_0000.nii.gz,ABDOMEN
1760,NKI-d23231-00-0424,2015-05-01,Portal,Too Late,Portal,portal_venous,Portal,11:55:42.205980,42942.20598,190.10401,9.85,85.98,3.0,Veneus laat 3.0 B30f,B30f,84.83,87.78,1.0210,NET_2787_0000.nii.gz,ABDOMEN

In [72]:
contrast_correct[cols][contrast_correct.SubjectKeyRadiology == 'NKI-d23231-00-0420']

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
1736,NKI-d23231-00-0420,2014-07-04,Portal,Just Right,Portal,portal_venous,Arterial,10:19:18.642500,37158.64250,33.29699,8.46,66.69,3.0,Arterieel 3.0 B30f,B30f,65.42,67.38,0.6966,NET_2725_0000.nii.gz,ABDOMEN
1737,NKI-d23231-00-0420,2014-07-04,Portal,Just Right,Portal,portal_venous,Portal,10:19:51.939490,37191.93949,235.57852,5.44,75.15,3.0,Veneus 3.0 B30f,B30f,71.16,77.74,2.4462,NET_2727_0000.nii.gz,ABDOMEN
1738,NKI-d23231-00-0420,2014-07-04,Portal,Too Late,Portal,portal_venous,Portal,10:23:47.518010,37427.51801,235.57852,5.44,69.71,3.0,Veneus laat 3.0 B30f,B30f,66.32,73.65,2.5375,NET_2728_0000.nii.gz,ABDOMEN
1739,NKI-d23231-00-0420,2015-07-07,Arterial,Too Early,Arterial,arterial_late,Arterial,11:29:51.640000,41391.64000,34.99000,38.18,32.28,3.0,Lever-Arterieel 3.0 B40f,B40f,31.21,33.41,0.8556,NET_2731_0000.nii.gz,ABDOMEN
1740,NKI-d23231-00-0420,2015-07-07,Portal,Just Right,Portal,portal_venous,Portal,11:30:26.630000,41426.63000,34.99000,38.18,70.46,3.0,Abd-Veneus 3.0 B40f,B40f,69.03,73.55,1.5919,NET_2729_0000.nii.gz,ABDOMEN
1741,NKI-d23231-00-0420,2018-01-15,Arterial,Just Right,Arterial,arterial_late,Arterial,10:48:17.897000,38897.89700,35.34900,43.58,30.33,3.0,Lever-Arterieel 3.0 I40f 2,I40f\2,28.49,32.14,1.5765,NET_2738_0000.nii.gz,ABDOMEN
1742,NKI-d23231-00-0420,2018-01-15,Portal,Just Right,Portal,portal_venous,Portal,10:48:53.246000,38933.24600,35.34900,43.58,73.91,3.0,Abd-Veneus 3.0 I40f 2,I40f\2,69.60,76.08,2.4007,NET_0179_0000.nii.gz,ABDOMEN
1743,NKI-d23231-00-0420,2018-12-21,Arterial,Just Right,Arterial,arterial_late,Arterial,12:04:2.752000,43442.75200,34.60000,24.90,43.76,1.0,Abd laat-art 1.0 I26f 2,I26f\2,39.89,50.48,3.9347,NET_2739_0000.nii.gz,ABDOMEN
1744,NKI-d23231-00-0420,2018-12-21,Portal,Just Right,Portal,portal_venous,NaN,12:04:37.352000,43477.35200,34.60000,24.90,68.66,1.0,Abdomen 1.0 I26f 2,I26f\2,63.74,73.35,3.1713,NET_2740_0000.nii.gz,ABDOMEN
1745,NKI-d23231-00-0420,2019-12-17,Arterial,Just Right,Arterial,arterial_late,Arterial,10:55:31.555000,39331.55500,33.24300,14.48,59.65,1.0,Abd laat-art 1.0 I26f 2,I26f\2,56.84,61.58,1.5813,NET_2741_0000.nii.gz,ABDOMEN
1746,NKI-d23231-00-0420,2019-12-17,Portal,Just Right,Portal,portal_venous,NaN,10:56:4.798000,39364.79800,33.24300,14.48,74.13,1.0,Abdomen 1.0 I26f 2,I26f\2,71.52,75.59,1.4206,NET_2742_0000.nii.gz,ABDOMEN
1747,NKI-d23231-00-0420,2022-05-09,Arterial,Just Right,Arterial,arterial_late,Arterial,15:34:19.869980,56059.86998,31.71779,34.44,38.54,1.5,Abdomen A 1.5 B25f,B25f,35.69,42.26,2.3557,NET_2748_0000.nii.gz,ABDOMEN
1748,NKI-d23231-00-0420,2022-05-09,Portal,Just Right,Portal,portal_venous,Portal,15:34:51.587770,56091.58777,31.71779,34.44,72.98,1.5,Abdomen V 1.5 B25f,B25f,71.23,74.93,1.3277,NET_2749_0000.nii.gz,ABDOMEN
1749,NKI-d23231-00-0420,2023-09-01,Arterial,Just Right,Arterial,arterial_late,Arterial,13:37:0.711000,49020.71100,36.89100,25.58,43.89,1.0,Abdomen Art 1.0 Br36 3,Br36f\3,41.37,46.98,2.0409,NET_2752_0000.nii.gz,ABDOMEN
1750,NKI-d23231-00-0420,2023-09-01,Portal,Just Right,Portal,portal_venous,Portal,13:37:37.602000,49057.60200,36.89100,25.58,69.47,1.0,Abdomen PV 1.0 Br36 3,Br36f\3,66.07,72.17,2.2617,NET_2753_0000.nii.gz,ABDOMEN

In [73]:
top_outliers.ProtocolName.value_counts()

ProtocolName
Abdomen V  1.5  B25f          12
Abdomen A  1.5  B25f          11
ABDOMEN A 1.0 FC01             4
ABDOMEN + C 1.0 FC01           4
Veneus 3.0 B30f                2
Veneus laat 3.0 B30f           2
ABDOMEN + C 1.0 FC02           2
ABDOMEN A 1.0 FC02             2
Abd art  1.0  I26f  2          1
Uitscheiding  1.0  I26f  2     1
Abd-Veneus  3.0  B40f          1
Lever-Laat ven  3.0  B40f      1
Vroeg Veneus 3.0 B30f          1
Laat Veneus 3.0 B30f           1
Delayed Phase  3.0  B25f       1
Venous Phase  3.0  B25f        1
Abd laat-art  1.0  I26f  2     1
ThorAbd   1.0  I26f  2         1
Abdomen V  3.0  B31f           1
Name: count, dtype: int64

### Only A and PV exams

In [74]:
# Include only exams with both arterial and portal
required_phases = {"Arterial", "Portal"}

subset = (
    contrast_correct
    .groupby(["SubjectKeyRadiology", "ExamDate"])
    .filter(lambda g: required_phases.issubset(set(g["contrast"])))
)

In [75]:
subset[cols].sort_values(by=["SubjectKeyRadiology", "ExamDate", "AcquisitionTime"])

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
0,NKI-d23231-00-0005,2010-02-04,Arterial,Too Early,Arterial,arterial_late,Arterial,11:18:35.166000,40715.16600,53.64779,37.96,39.85,1.5,Abdomen A 1.5 B25f,B25f,39.30,40.31,0.3781,NET_0000_0000.nii.gz,ABDOMEN
1,NKI-d23231-00-0005,2010-02-04,Portal,Just Right,Portal,portal_venous,Portal,11:19:28.813790,40768.81379,53.64779,37.96,77.81,1.5,Abdomen V 1.5 B25f,B25f,74.64,80.58,1.9790,NET_0007_0000.nii.gz,ABDOMEN
2,NKI-d23231-00-0005,2012-06-18,Portal,Too Early,Portal,portal_venous,NaN,14:08:42.350000,50922.35000,33.40000,25.52,76.14,1.0,ABDOMEN + C 1.0 FC02,FC02,75.02,77.07,0.6825,NET_0009_0000.nii.gz,ABDOMEN
3,NKI-d23231-00-0005,2012-06-18,Arterial,Too Early,Arterial,arterial_late,Arterial,14:08:8.950000,50888.95000,33.40000,25.52,50.62,1.0,ABDOMEN A 1.0 FC02,FC02,46.69,56.02,3.0884,NET_0050_0000.nii.gz,ABDOMEN
4,NKI-d23231-00-0005,2022-05-11,Arterial,Just Right,Arterial,arterial_late,Arterial,13:58:42.277600,50322.27760,30.84280,41.10,38.54,1.5,Abdomen A 1.5 B25f,B25f,34.43,41.45,2.6207,NET_0013_0000.nii.gz,ABDOMEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2477,NKI-d23231-00-0887,2023-08-30,Portal,Just Right,Portal,portal_venous,Portal,13:15:45.600000,47745.60000,28.90000,23.61,78.83,1.0,THORABD PV Body 1.0 CE THORABD PV,FC01,77.06,82.48,1.9154,NET_5822_0000.nii.gz,ABDOMEN
2478,NKI-d23231-00-0888,2022-04-20,Arterial,Just Right,Arterial,arterial_late,Arterial,15:12:44.337430,54764.33743,31.78189,23.45,56.94,1.5,Abdomen A 1.5 B25f,B25f,53.09,65.94,4.8974,NET_5826_0000.nii.gz,ABDOMEN
2479,NKI-d23231-00-0888,2022-04-20,Portal,Just Right,Portal,portal_venous,Portal,15:13:16.119320,54796.11932,31.78189,23.45,80.39,1.5,Abdomen V 1.5 B25f,B25f,78.27,82.66,1.4937,NET_5827_0000.nii.gz,ABDOMEN
2480,NKI-d23231-00-0888,2023-04-24,Arterial,Just Right,Arterial,arterial_late,Arterial,12:05:45.561000,43545.56100,34.57700,18.09,59.19,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.14,61.54,1.8509,NET_5828_0000.nii.gz,ABDOMEN
2481,NKI-d23231-00-0888,2023-04-24,Portal,Just Right,Portal,portal_venous,NaN,12:06:20.138000,43580.13800,34.57700,18.09,77.28,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,74.66,78.94,1.6271,NET_5829_0000.nii.gz,ABDOMEN

In [76]:
subset["time_interval"] = (
    subset
    .groupby(unique_keys)["AcquisitionTime_sec"]
    .diff()
    .shift(-1)
    .ffill(limit = 1)
)

subset["TS_time_interval"] = (
    subset
    .groupby(unique_keys)["pi_time"]
    .diff()
    .shift(-1)
    .ffill(limit = 1)
    )

subset['TS_time_interval'] = subset['TS_time_interval'].apply(lambda x: abs(x))
subset['time_interval'] = subset['time_interval'].apply(lambda x: abs(x))

subset= subset.dropna(subset=["time_interval"],ignore_index=True)

print("MAE:", mean_absolute_error(subset.time_interval,subset.TS_time_interval))
print("RMSE:", root_mean_squared_error(subset.time_interval,subset.TS_time_interval))

subset['error'] = abs(subset.TS_time_interval - subset.time_interval)
# cols.append('error')

subset[cols].sort_values(by=["SubjectKeyRadiology", "ExamDate", "AcquisitionTime", "time_interval"])

MAE: 17.35357067681887
RMSE: 25.05488653514083

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
0,NKI-d23231-00-0005,2010-02-04,Arterial,Too Early,Arterial,arterial_late,Arterial,11:18:35.166000,40715.16600,53.64779,37.96,39.85,1.5,Abdomen A 1.5 B25f,B25f,39.30,40.31,0.3781,NET_0000_0000.nii.gz,ABDOMEN
1,NKI-d23231-00-0005,2010-02-04,Portal,Just Right,Portal,portal_venous,Portal,11:19:28.813790,40768.81379,53.64779,37.96,77.81,1.5,Abdomen V 1.5 B25f,B25f,74.64,80.58,1.9790,NET_0007_0000.nii.gz,ABDOMEN
2,NKI-d23231-00-0005,2012-06-18,Portal,Too Early,Portal,portal_venous,NaN,14:08:42.350000,50922.35000,33.40000,25.52,76.14,1.0,ABDOMEN + C 1.0 FC02,FC02,75.02,77.07,0.6825,NET_0009_0000.nii.gz,ABDOMEN
3,NKI-d23231-00-0005,2012-06-18,Arterial,Too Early,Arterial,arterial_late,Arterial,14:08:8.950000,50888.95000,33.40000,25.52,50.62,1.0,ABDOMEN A 1.0 FC02,FC02,46.69,56.02,3.0884,NET_0050_0000.nii.gz,ABDOMEN
4,NKI-d23231-00-0005,2022-05-11,Arterial,Just Right,Arterial,arterial_late,Arterial,13:58:42.277600,50322.27760,30.84280,41.10,38.54,1.5,Abdomen A 1.5 B25f,B25f,34.43,41.45,2.6207,NET_0013_0000.nii.gz,ABDOMEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2359,NKI-d23231-00-0887,2023-08-30,Portal,Just Right,Portal,portal_venous,Portal,13:15:45.600000,47745.60000,28.90000,23.61,78.83,1.0,THORABD PV Body 1.0 CE THORABD PV,FC01,77.06,82.48,1.9154,NET_5822_0000.nii.gz,ABDOMEN
2360,NKI-d23231-00-0888,2022-04-20,Arterial,Just Right,Arterial,arterial_late,Arterial,15:12:44.337430,54764.33743,31.78189,23.45,56.94,1.5,Abdomen A 1.5 B25f,B25f,53.09,65.94,4.8974,NET_5826_0000.nii.gz,ABDOMEN
2361,NKI-d23231-00-0888,2022-04-20,Portal,Just Right,Portal,portal_venous,Portal,15:13:16.119320,54796.11932,31.78189,23.45,80.39,1.5,Abdomen V 1.5 B25f,B25f,78.27,82.66,1.4937,NET_5827_0000.nii.gz,ABDOMEN
2362,NKI-d23231-00-0888,2023-04-24,Arterial,Just Right,Arterial,arterial_late,Arterial,12:05:45.561000,43545.56100,34.57700,18.09,59.19,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.14,61.54,1.8509,NET_5828_0000.nii.gz,ABDOMEN
2363,NKI-d23231-00-0888,2023-04-24,Portal,Just Right,Portal,portal_venous,NaN,12:06:20.138000,43580.13800,34.57700,18.09,77.28,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,74.66,78.94,1.6271,NET_5829_0000.nii.gz,ABDOMEN

In [77]:
subset.contrast.value_counts()

contrast
Portal      1183
Arterial    1181
Name: count, dtype: int64

In [78]:
multi_phase = (
    subset
    .groupby(unique_keys)
    .filter(lambda x: len(x) > 2)
)

multi_phase[cols].sort_values(by=['SubjectKeyRadiology', 'ExamDate', 'AcquisitionTime'])

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
618,NKI-d23231-00-0149,2007-03-20,Arterial,Just Right,Arterial,arterial_late,Arterial,12:56:51.365720,46611.36572,36.47408,17.45,52.44,3.0,Arterial Phase 3.0 B25f,B25f,49.95,56.62,2.3829,NET_0262_0000.nii.gz,ABDOMEN
619,NKI-d23231-00-0149,2007-03-20,Portal,Just Right,Portal,portal_venous,Portal,12:57:27.839800,46647.83980,106.52620,10.31,69.89,3.0,Venous Phase 3.0 B25f,B25f,65.94,72.98,2.3329,NET_0087_0000.nii.gz,ABDOMEN
620,NKI-d23231-00-0149,2007-03-20,Portal,Just Right,Portal,portal_venous,Late Phase,12:59:14.366000,46754.36600,106.52620,10.31,80.20,3.0,Delayed Phase 3.0 B25f,B25f,76.86,83.44,2.5671,NET_0263_0000.nii.gz,ABDOMEN
1911,NKI-d23231-00-0535,2019-09-18,Arterial,Just Right,Arterial,arterial_late,Arterial,11:44:33.167000,42273.16700,0.00000,0.26,53.58,1.0,Abd laat-art 1.0 I26f 2 iMAR,I26f\2,47.59,59.49,4.9791,NET_3754_0000.nii.gz,ABDOMEN
1912,NKI-d23231-00-0535,2019-09-18,Arterial,Just Right,Arterial,arterial_late,Arterial,11:44:33.167000,42273.16700,37.93800,19.33,53.84,1.0,Abd laat-art 1.0 I26f 2,I26f\2,48.53,59.80,4.8582,NET_3755_0000.nii.gz,ABDOMEN
1913,NKI-d23231-00-0535,2019-09-18,Portal,Just Right,Portal,portal_venous,NaN,11:45:11.105000,42311.10500,0.00000,2.17,73.17,1.0,Abdomen 1.0 I26f 2 iMAR,I26f\2,70.52,75.75,1.8035,NET_3756_0000.nii.gz,ABDOMEN
1914,NKI-d23231-00-0535,2019-09-18,Portal,Just Right,Portal,portal_venous,NaN,11:45:11.105000,42311.10500,0.00000,2.17,71.00,1.0,Abdomen 1.0 I26f 2,I26f\2,69.38,73.31,1.3085,NET_3757_0000.nii.gz,ABDOMEN
2191,NKI-d23231-00-0793,2017-10-03,Arterial,Just Right,Arterial,arterial_early,NaN,12:27:31.279000,44851.27900,17.49800,39.39,29.57,3.0,Art.Lever+thora 3.0 B40f,B40f,27.00,31.50,1.4892,NET_0439_0000.nii.gz,ABDOMEN
2192,NKI-d23231-00-0793,2017-10-03,Portal,Just Right,Portal,portal_venous,Portal,12:27:48.777000,44868.77700,192.55400,2.00,68.96,3.0,Abd-Veneus 3.0 B40f,B40f,67.37,72.08,1.6875,NET_5270_0000.nii.gz,ABDOMEN
2193,NKI-d23231-00-0793,2017-10-03,Portal,Too Late,Portal,portal_venous,Portal,12:31:1.331000,45061.33100,192.55400,2.00,66.96,3.0,Lever-Laat ven 3.0 B40f,B40f,65.98,68.29,0.8409,NET_5273_0000.nii.gz,ABDOMEN

In [79]:
multiphase_idx = list(multi_phase.index)

subset_cleaned = subset[cols].drop(multiphase_idx)
subset_cleaned.reset_index(drop=True, inplace=True)
subset_cleaned

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,time_interval,TS_time_interval,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
0,NKI-d23231-00-0005,2010-02-04,Arterial,Too Early,Arterial,arterial_late,Arterial,11:18:35.166000,40715.16600,53.64779,37.96,39.85,1.5,Abdomen A 1.5 B25f,B25f,39.30,40.31,0.3781,NET_0000_0000.nii.gz,ABDOMEN
1,NKI-d23231-00-0005,2010-02-04,Portal,Just Right,Portal,portal_venous,Portal,11:19:28.813790,40768.81379,53.64779,37.96,77.81,1.5,Abdomen V 1.5 B25f,B25f,74.64,80.58,1.9790,NET_0007_0000.nii.gz,ABDOMEN
2,NKI-d23231-00-0005,2012-06-18,Portal,Too Early,Portal,portal_venous,NaN,14:08:42.350000,50922.35000,33.40000,25.52,76.14,1.0,ABDOMEN + C 1.0 FC02,FC02,75.02,77.07,0.6825,NET_0009_0000.nii.gz,ABDOMEN
3,NKI-d23231-00-0005,2012-06-18,Arterial,Too Early,Arterial,arterial_late,Arterial,14:08:8.950000,50888.95000,33.40000,25.52,50.62,1.0,ABDOMEN A 1.0 FC02,FC02,46.69,56.02,3.0884,NET_0050_0000.nii.gz,ABDOMEN
4,NKI-d23231-00-0005,2022-05-11,Arterial,Just Right,Arterial,arterial_late,Arterial,13:58:42.277600,50322.27760,30.84280,41.10,38.54,1.5,Abdomen A 1.5 B25f,B25f,34.43,41.45,2.6207,NET_0013_0000.nii.gz,ABDOMEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2349,NKI-d23231-00-0887,2023-08-30,Portal,Just Right,Portal,portal_venous,Portal,13:15:45.600000,47745.60000,28.90000,23.61,78.83,1.0,THORABD PV Body 1.0 CE THORABD PV,FC01,77.06,82.48,1.9154,NET_5822_0000.nii.gz,ABDOMEN
2350,NKI-d23231-00-0888,2022-04-20,Arterial,Just Right,Arterial,arterial_late,Arterial,15:12:44.337430,54764.33743,31.78189,23.45,56.94,1.5,Abdomen A 1.5 B25f,B25f,53.09,65.94,4.8974,NET_5826_0000.nii.gz,ABDOMEN
2351,NKI-d23231-00-0888,2022-04-20,Portal,Just Right,Portal,portal_venous,Portal,15:13:16.119320,54796.11932,31.78189,23.45,80.39,1.5,Abdomen V 1.5 B25f,B25f,78.27,82.66,1.4937,NET_5827_0000.nii.gz,ABDOMEN
2352,NKI-d23231-00-0888,2023-04-24,Arterial,Just Right,Arterial,arterial_late,Arterial,12:05:45.561000,43545.56100,34.57700,18.09,59.19,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.14,61.54,1.8509,NET_5828_0000.nii.gz,ABDOMEN
2353,NKI-d23231-00-0888,2023-04-24,Portal,Just Right,Portal,portal_venous,NaN,12:06:20.138000,43580.13800,34.57700,18.09,77.28,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,74.66,78.94,1.6271,NET_5829_0000.nii.gz,ABDOMEN

In [80]:
print("MAE:", mean_absolute_error(subset_cleaned.time_interval,subset_cleaned.TS_time_interval))
print("RMSE:", root_mean_squared_error(subset_cleaned.time_interval,subset_cleaned.TS_time_interval))

MAE: 17.156404672897114
RMSE: 24.314396961082945