# TotalSegmentator Baseline

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import os

## Data Loading

### TS results

In [3]:
folder = "/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/"

radiomics = pd.DataFrame()
for subdir in os.listdir(folder):
    for file_path in os.listdir(os.path.join(folder, subdir)):
        if file_path != "jsons":
            print(file_path)

contrast_phase_results_batch3.csv
contrast_phase_results_batch2.csv
contrast_phase_results_batch1.csv
contrast_phase_results_batch0.csv
contrast_phase_results_batch3.csv
contrast_phase_results_batch2.csv
contrast_phase_results_batch1.csv
contrast_phase_results_batch0.csv

In [4]:
folder = "/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/"

dfs = []
for subdir in os.listdir(folder):
    for file_path in os.listdir(os.path.join(folder, subdir)):
        if file_path != "jsons":
            data = pd.read_csv(os.path.join(folder, subdir, file_path))
            dfs.append(data)

ts_data = pd.concat(dfs, ignore_index=True)
ts_data   # Error processing /mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/NKI-d23231-00-0818_20190322_kalina99_5441.nii.gz: Command '['totalseg_get_phase', '-i', np.str_('/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/NKI-d23231-00-0818_20190322_kalina99_5441.nii.gz'), '-o', '/projects/net_contrast_classification/contrast_phase/total_seg_output/NKI-d23231-00-0818_20190322_kalina99_5441_phase.json']' returned non-zero exit status 1.
          # Error processing /mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20100107_kalina99_0195.nii.gz: Command '['totalseg_get_phase', '-i', np.str_('/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20100107_kalina99_0195.nii.gz'), '-o', '/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/vol2/jsons/NKI-d23231-00-0218_20100107_kalina99_0195_phase.json']' returned non-zero exit status 1.
          # Error processing /mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20141212_kalina99_0205.nii.gz: Command '['totalseg_get_phase', '-i', np.str_('/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET/not_on_server/NKI-d23231-00-0218_20141212_kalina99_0205.nii.gz'), '-o', '/projects/net_contrast_classification/contrast_phase/TS/total_seg_output/vol2/jsons/NKI-d23231-00-0218_20141212_kalina99_0205_phase.json']' returned non-zero exit status 1.

,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,file
0,62.32,portal_venous,1.0,59.75,65.18,2.0337,NKI-d23231-00-0510_20180213_kalina99_3504.nii.gz
1,78.85,portal_venous,1.0,75.80,81.02,2.1212,NKI-d23231-00-0510_20180213_kalina99_3505.nii.gz
2,62.80,portal_venous,1.0,60.64,65.12,1.6836,NKI-d23231-00-0510_20180516_kalina99_3506.nii.gz
3,75.56,portal_venous,1.0,74.42,76.31,0.7562,NKI-d23231-00-0510_20180516_kalina99_3507.nii.gz
4,79.19,portal_venous,1.0,78.23,80.66,0.9207,NKI-d23231-00-0510_20180924_kalina99_3508.nii.gz
...,...,...,...,...,...,...,...
8725,51.08,arterial_late,0.7,47.71,54.20,2.6832,NKI-d23231-00-0155_20041209_kalina99_0344.nii.gz
8726,98.72,portal_venous,0.7,83.66,110.93,9.1340,NKI-d23231-00-0155_20050915_kalina99_0345.nii.gz
8727,65.10,portal_venous,1.0,64.18,65.72,0.5152,NKI-d23231-00-0155_20070712_kalina99_0351.nii.gz
8728,0.14,native,1.0,-0.77,1.10,0.7212,NKI-d23231-00-0155_20071112_kalina99_0353.nii.gz
8729,0.40,native,1.0,-0.47,2.11,0.9237,NKI-d23231-00-0155_20080219_kalina99_0355.nii.gz

### Merge

In [5]:
data = pd.read_csv("/projects/net_contrast_classification/contrast_phase/data/cleaned_data/final_data.csv")
merged_data = pd.merge(data, ts_data, left_on=["MatchKey"], right_on=["file"], how = 'left', suffixes=('', '_ts'))
merged_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8335 entries, 0 to 8334
Data columns (total 54 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   MatchKey                            8335 non-null   str
 1   Original File                       8335 non-null   str
 2   Destination Folder                  8335 non-null   str
 3   New File                            8335 non-null   str
 4   SubjectKeyRadiology                 8335 non-null   str
 5   ExamDate                            8335 non-null   str
 6   file                                8335 non-null   str
 7   is_liver_imaged                     8335 non-null   str
 8   contrast                            8335 non-null   str
 9   phase_timing                        8335 non-null   str
 10  is_lesionfree                       8335 non-null   str
 11  ai_segmentation_quality             4156 non-null   float64
 12  manual_segmentation_confidence      4156 non-null   float64
 13  adjustment_segmentation_difficulty  4156 non-null   float64
 14  high_signal_to_noise                6295 non-null   object
 15  metal_artifacts                     6295 non-null   object
 16  patient_motion                      6295 non-null   object
 17  other                               187 non-null    str
 18  comment                             664 non-null    str
 19  time-stamp                          8335 non-null   float64
 20  Modality                            8335 non-null   str
 21  ImagingFrequency                    8335 non-null   int64
 22  Manufacturer                        8335 non-null   str
 23  ManufacturersModelName              8335 non-null   str
 24  DeviceSerialNumber                  7995 non-null   float64
 25  PatientPosition                     8335 non-null   str
 26  SoftwareVersions                    8335 non-null   str
 27  SeriesDescription                   8335 non-null   str
 28  ProtocolName                        8335 non-null   str
 29  ScanOptions                         4022 non-null   str
 30  ImageType                           8335 non-null   str
 31  SeriesNumber                        8335 non-null   int64
 32  AcquisitionTime                     8335 non-null   str
 33  AcquisitionNumber                   8040 non-null   float64
 34  ConvolutionKernel                   8335 non-null   str
 35  ExposureTime                        8045 non-null   float64
 36  XRayTubeCurrent                     8335 non-null   float64
 37  XRayExposure                        8335 non-null   float64
 38  ImageOrientationPatientDICOM        8335 non-null   str
 39  ConversionSoftware                  8335 non-null   str
 40  ConversionSoftwareVersion           8335 non-null   str
 41  BodyPartExamined                    8294 non-null   str
 42  RawImage                            2 non-null      object
 43  SliceThickness                      8321 non-null   float64
 44  AcquisitionTime_sec                 8335 non-null   float64
 45  DICOM_phase                         4800 non-null   str
 46  exist_on_server                     5430 non-null   str
 47  pi_time                             8333 non-null   float64
 48  phase                               8333 non-null   str
 49  probability                         8333 non-null   float64
 50  pi_time_min                         8333 non-null   float64
 51  pi_time_max                         8333 non-null   float64
 52  stddev                              8333 non-null   float64
 53  file_ts                             8333 non-null   str
dtypes: float64(16), int64(2), object(4), str(32)
memory usage: 8.0+ MB

In [6]:
merged_data[merged_data.file_ts.isna() & merged_data.MatchKey.notna()
            ][["SubjectKeyRadiology", 'ExamDate', 'Destination Folder',
               'file',  "MatchKey", "file", "file_ts", 'exist_on_server']]

,SubjectKeyRadiology,ExamDate,Destination Folder,file,MatchKey,file,file_ts,exist_on_server
1344,NKI-d23231-00-0082,2019-08-23,DICOM-batch1-kalina99,NET_0566_0000.nii.gz,NKI-d23231-00-0082_20190823_kalina99_0566.nii.gz,NET_0566_0000.nii.gz,NaN,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
1654,NKI-d23231-00-0169,2018-05-02,DICOM-batch2-giovanni01,NET_0053_0000.nii.gz,NKI-d23231-00-0169_20180502_giovanni01_0053.ni...,NET_0053_0000.nii.gz,NaN,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...

In [7]:
print("True contrast labels:\n", merged_data["contrast"].value_counts())
print("\n")
print("True timing labels:\n",merged_data["phase_timing"].value_counts())
print('\n')
print("TS labels:\n",merged_data["phase"].value_counts())

True contrast labels:
 contrast
Portal          3730
Arterial        2540
Non-contrast    2065
Name: count, dtype: int64


True timing labels:
 phase_timing
Just Right      5150
Non-contrast    2065
Too Early        945
Too Late         175
Name: count, dtype: int64


TS labels:
 phase
portal_venous     4537
native            2008
arterial_late     1763
arterial_early      25
Name: count, dtype: int64

In [8]:
merged_data.phase.info()

<class 'pandas.Series'>
RangeIndex: 8335 entries, 0 to 8334
Series name: phase
Non-Null Count  Dtype
--------------  -----
8333 non-null   str
dtypes: str(1)
memory usage: 158.4 KB

In [9]:
merged_data["TS_contrast"] = merged_data["phase"].str.split("_").str[0].str.capitalize()
merged_data.loc[merged_data["phase"].str.contains("native", na=False), "TS_contrast"] = "Non-contrast"

# merged_data["TS_timing"] = merged_data["phase"].apply(lambda x: x.split("_")[1].capitalize() if "_" in x else "Non-contrast")
# merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Just Right" if x == 'Venous' else x)
# merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Too Early" if x == 'Early' else x)
# merged_data["TS_timing"] = merged_data["TS_timing"].apply(lambda x: "Too Late" if x == 'Late' else x)


print('After renaming:')
print("True labels:\n", merged_data["contrast"].value_counts())
print("\n")
print("TS labels:\n",merged_data["TS_contrast"].value_counts()) # Early AP and Late AP from TS are merged in AP

After renaming:
True labels:
 contrast
Portal          3730
Arterial        2540
Non-contrast    2065
Name: count, dtype: int64


TS labels:
 TS_contrast
Portal          4537
Non-contrast    2008
Arterial        1788
Name: count, dtype: int64

In [10]:
merged_data.TS_contrast.info()

<class 'pandas.Series'>
RangeIndex: 8335 entries, 0 to 8334
Series name: TS_contrast
Non-Null Count  Dtype
--------------  -----
8333 non-null   object
dtypes: object(1)
memory usage: 65.2+ KB

In [11]:
merged_data.to_csv("/projects/net_contrast_classification/contrast_phase/TS/TS_results.csv", index = False)

### Ground truth inconsistencies

In [12]:
merged_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8335 entries, 0 to 8334
Data columns (total 55 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   MatchKey                            8335 non-null   str
 1   Original File                       8335 non-null   str
 2   Destination Folder                  8335 non-null   str
 3   New File                            8335 non-null   str
 4   SubjectKeyRadiology                 8335 non-null   str
 5   ExamDate                            8335 non-null   str
 6   file                                8335 non-null   str
 7   is_liver_imaged                     8335 non-null   str
 8   contrast                            8335 non-null   str
 9   phase_timing                        8335 non-null   str
 10  is_lesionfree                       8335 non-null   str
 11  ai_segmentation_quality             4156 non-null   float64
 12  manual_segmentation_confidence      4156 non-null   float64
 13  adjustment_segmentation_difficulty  4156 non-null   float64
 14  high_signal_to_noise                6295 non-null   object
 15  metal_artifacts                     6295 non-null   object
 16  patient_motion                      6295 non-null   object
 17  other                               187 non-null    str
 18  comment                             664 non-null    str
 19  time-stamp                          8335 non-null   float64
 20  Modality                            8335 non-null   str
 21  ImagingFrequency                    8335 non-null   int64
 22  Manufacturer                        8335 non-null   str
 23  ManufacturersModelName              8335 non-null   str
 24  DeviceSerialNumber                  7995 non-null   float64
 25  PatientPosition                     8335 non-null   str
 26  SoftwareVersions                    8335 non-null   str
 27  SeriesDescription                   8335 non-null   str
 28  ProtocolName                        8335 non-null   str
 29  ScanOptions                         4022 non-null   str
 30  ImageType                           8335 non-null   str
 31  SeriesNumber                        8335 non-null   int64
 32  AcquisitionTime                     8335 non-null   str
 33  AcquisitionNumber                   8040 non-null   float64
 34  ConvolutionKernel                   8335 non-null   str
 35  ExposureTime                        8045 non-null   float64
 36  XRayTubeCurrent                     8335 non-null   float64
 37  XRayExposure                        8335 non-null   float64
 38  ImageOrientationPatientDICOM        8335 non-null   str
 39  ConversionSoftware                  8335 non-null   str
 40  ConversionSoftwareVersion           8335 non-null   str
 41  BodyPartExamined                    8294 non-null   str
 42  RawImage                            2 non-null      object
 43  SliceThickness                      8321 non-null   float64
 44  AcquisitionTime_sec                 8335 non-null   float64
 45  DICOM_phase                         4800 non-null   str
 46  exist_on_server                     5430 non-null   str
 47  pi_time                             8333 non-null   float64
 48  phase                               8333 non-null   str
 49  probability                         8333 non-null   float64
 50  pi_time_min                         8333 non-null   float64
 51  pi_time_max                         8333 non-null   float64
 52  stddev                              8333 non-null   float64
 53  file_ts                             8333 non-null   str
 54  TS_contrast                         8333 non-null   object
dtypes: float64(16), int64(2), object(5), str(32)
memory usage: 8.1+ MB

In [13]:
merged_data.contrast.value_counts()

contrast
Portal          3730
Arterial        2540
Non-contrast    2065
Name: count, dtype: int64

In [14]:
merged_data.DICOM_phase.value_counts()

DICOM_phase
Arterial        2264
Non-contrast    1512
Portal          1023
Late Venous        1
Name: count, dtype: int64

In [15]:
dicom_labels = merged_data[merged_data["DICOM_phase"].notna()]
diff_dicom = dicom_labels[(dicom_labels["DICOM_phase"] != dicom_labels["contrast"])][["MatchKey","ProtocolName", "contrast", "phase_timing", "phase", "DICOM_phase"]]

print(f"Entries where the contrast annotation != (non-null) DICOM label: {len(diff_dicom)}/ {len(dicom_labels)} ~ {round(len(diff_dicom)/len(dicom_labels), 3)}")

diff_dicom.head(10)

Entries where the contrast annotation != (non-null) DICOM label: 48/ 4800 ~ 0.01

,MatchKey,ProtocolName,contrast,phase_timing,phase,DICOM_phase
490,NKI-d23231-00-0007_20100517_kalina09_0043.nii.gz,Abdomen V 2mm,Arterial,Too Late,portal_venous,Portal
708,NKI-d23231-00-0075_20170912_kalina14_0029.nii.gz,axiaal 3 mm arterieel,Portal,Just Right,portal_venous,Arterial
797,NKI-d23231-00-0005_20200128_kalina15_0059.nii.gz,Abdomen A 1.5 B25f,Non-contrast,Non-contrast,arterial_late,Arterial
807,NKI-d23231-00-0005_20200128_kalina99_0012.nii.gz,Abdomen V 1.5 B25f,Non-contrast,Non-contrast,arterial_late,Portal
841,NKI-d23231-00-0033_20171030_kalina99_0047.nii.gz,Abdomen A 1.5 B25f,Portal,Just Right,portal_venous,Arterial
1225,NKI-d23231-00-0073_20090402_kalina99_0444.nii.gz,Laat Veneus 3.0 B30f,Portal,Just Right,portal_venous,Late Venous
1336,NKI-d23231-00-0081_20160111_kalina99_0558.nii.gz,ABDOMEN A 1.0 FC01,Portal,Just Right,portal_venous,Arterial
1435,NKI-d23231-00-0186_20141010_david01_0028.nii.gz,ABDOMEN A 1.0 FC01,Portal,Too Early,portal_venous,Arterial
1699,NKI-d23231-00-0192_20051202_giovanni01_0103.ni...,Abdomen art 1.5 B30f,Non-contrast,Non-contrast,arterial_early,Arterial
1771,NKI-d23231-00-0146_20190502_giovanni01_0179.ni...,Abd laat-art 1.0 I26f 2,Portal,Too Early,arterial_late,Arterial

In [16]:
ts_agreemnent = merged_data[(merged_data["DICOM_phase"] == merged_data["TS_contrast"])
                            & (merged_data["contrast"] == merged_data["TS_contrast"])
                            ][["MatchKey","ProtocolName", "contrast", "phase_timing", "phase", "DICOM_phase"]]


print(f"Entries where the radiologist's annotations, the DICOM label and the TS label agree: {len(ts_agreemnent)}/ {len(dicom_labels)} ~ {round(len(ts_agreemnent)/len(dicom_labels), 3)}")


ts_agreemnent

Entries where the radiologist's annotations, the DICOM label and the TS label agree: 4154/ 4800 ~ 0.865

,MatchKey,ProtocolName,contrast,phase_timing,phase,DICOM_phase
1,NKI-d23231-00-0070_20150821_kalina01_0001.nii.gz,LEVER -C 1.0 FC03,Non-contrast,Non-contrast,native,Non-contrast
4,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz,Abdomen V 1.5 B25f,Portal,Just Right,portal_venous,Portal
5,NKI-d23231-00-0049_20090212_kalina01_0005.nii.gz,Abdomen V 1.5 B25f,Portal,Just Right,portal_venous,Portal
6,NKI-d23231-00-0055_20140908_kalina01_0006.nii.gz,ABDOMEN A 1.0 FC01,Arterial,Just Right,arterial_late,Arterial
7,NKI-d23231-00-0054_20150409_kalina01_0007.nii.gz,Abdomen A 3.0 B31f,Arterial,Too Early,arterial_late,Arterial
...,...,...,...,...,...,...
8327,NKI-d23231-00-0887_20230830_kalina99_5822.nii.gz,THORABD PV Body 1.0 CE THORABD PV,Portal,Just Right,portal_venous,Portal
8328,NKI-d23231-00-0888_20210218_kalina99_5823.nii.gz,Bobuik art 1.0 I40f 2,Arterial,Too Early,arterial_late,Arterial
8329,NKI-d23231-00-0888_20220420_kalina99_5826.nii.gz,Abdomen A 1.5 B25f,Arterial,Just Right,arterial_late,Arterial
8330,NKI-d23231-00-0888_20220420_kalina99_5827.nii.gz,Abdomen V 1.5 B25f,Portal,Just Right,portal_venous,Portal
8331,NKI-d23231-00-0888_20230424_kalina99_5828.nii.gz,Abd laat-art 1.0 Bv38 2,Arterial,Just Right,arterial_late,Arterial

## Arterial vs. Portal vs. NC

In [17]:
merged_data.head(5)

,MatchKey,Original File,Destination Folder,New File,SubjectKeyRadiology,ExamDate,file,is_liver_imaged,contrast,phase_timing,...,DICOM_phase,exist_on_server,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,file_ts,TS_contrast
0,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz,../DICOM-batch1\NKI-d23231-00-0063\20120416 CT...,DICOM-batch1-kalina01,NET_0000_0000.nii.gz,NKI-d23231-00-0063,2012-04-16,NET_0000_0000.nii.gz,Partially,Arterial,Too Early,...,Arterial,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,62.02,portal_venous,1.0,56.91,66.18,3.0706,NKI-d23231-00-0063_20120416_kalina01_0000.nii.gz,Portal
1,NKI-d23231-00-0070_20150821_kalina01_0001.nii.gz,../DICOM-batch1\NKI-d23231-00-0070\20150821 CT...,DICOM-batch1-kalina01,NET_0001_0000.nii.gz,NKI-d23231-00-0070,2015-08-21,NET_0001_0000.nii.gz,Yes,Non-contrast,Non-contrast,...,Non-contrast,NaN,-0.23,native,1.0,-0.83,0.21,0.3632,NKI-d23231-00-0070_20150821_kalina01_0001.nii.gz,Non-contrast
2,NKI-d23231-00-0036_20140218_kalina01_0002.nii.gz,../DICOM-batch1\NKI-d23231-00-0036\20140218 CT...,DICOM-batch1-kalina01,NET_0002_0000.nii.gz,NKI-d23231-00-0036,2014-02-18,NET_0002_0000.nii.gz,Yes,Portal,Just Right,...,NaN,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,78.87,portal_venous,1.0,76.97,80.38,1.1980,NKI-d23231-00-0036_20140218_kalina01_0002.nii.gz,Portal
3,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz,../DICOM-batch1\NKI-d23231-00-0071\20130924 CT...,DICOM-batch1-kalina01,NET_0003_0000.nii.gz,NKI-d23231-00-0071,2013-09-24,NET_0003_0000.nii.gz,Yes,Arterial,Just Right,...,NaN,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,69.99,portal_venous,1.0,67.83,72.74,1.7276,NKI-d23231-00-0071_20130924_kalina01_0003.nii.gz,Portal
4,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz,../DICOM-batch1\NKI-d23231-00-0077\20141222 CT...,DICOM-batch1-kalina01,NET_0004_0000.nii.gz,NKI-d23231-00-0077,2014-12-22,NET_0004_0000.nii.gz,Yes,Portal,Just Right,...,Portal,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,74.84,portal_venous,1.0,66.55,82.59,5.8700,NKI-d23231-00-0077_20141222_kalina01_0004.nii.gz,Portal

In [20]:
merged_data[merged_data.TS_contrast.isna()]

,MatchKey,Original File,Destination Folder,New File,SubjectKeyRadiology,ExamDate,file,is_liver_imaged,contrast,phase_timing,...,DICOM_phase,exist_on_server,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,file_ts,TS_contrast
1344,NKI-d23231-00-0082_20190823_kalina99_0566.nii.gz,../DICOM-batch1\NKI-d23231-00-0082\20190823 CT...,DICOM-batch1-kalina99,NET_0566_0000.nii.gz,NKI-d23231-00-0082,2019-08-23,NET_0566_0000.nii.gz,Yes,Portal,Too Late,...,Portal,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654,NKI-d23231-00-0169_20180502_giovanni01_0053.ni...,../DICOM-batch2\NKI-d23231-00-0169\20180502 CT...,DICOM-batch2-giovanni01,NET_0053_0000.nii.gz,NKI-d23231-00-0169,2018-05-02,NET_0053_0000.nii.gz,Yes,Portal,Just Right,...,NaN,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

test_data = merged_data[(merged_data.contrast != '0') & (merged_data.TS_contrast.notna())]

le = LabelEncoder()
y_true = le.fit_transform(test_data["contrast"])
y_pred = le.fit_transform(test_data['TS_contrast'])

print('Contrast classification accuracy:', round(accuracy_score(y_true, y_pred),3))
print("Classification report:\n", classification_report(y_true, y_pred, target_names=le.classes_))

Contrast classification accuracy: 0.895
Classification report:
               precision    recall  f1-score   support

    Arterial       0.98      0.69      0.81      2540
Non-contrast       1.00      0.97      0.99      2065
      Portal       0.82      0.99      0.90      3728

    accuracy                           0.90      8333
   macro avg       0.93      0.88      0.90      8333
weighted avg       0.91      0.90      0.89      8333

In [22]:
misclassified = test_data[
    test_data['contrast'] != test_data['TS_contrast']
]
print('Number of misclassifications:', len(misclassified))
print("Confusion matrix:")
pd.crosstab(
    test_data['contrast'],
    test_data['TS_contrast'],
    margins=True
)

Number of misclassifications: 873
Confusion matrix:

TS_contrast   Arterial  Non-contrast  Portal   All
contrast
Arterial          1747             0     793  2540
Non-contrast        20          2007      38  2065
Portal              21             1    3706  3728
All               1788          2008    4537  8333

In [24]:
# 25 entries where DICOM contrast = TS contrast but radiologists put different label

misclass_correct_dicom = misclassified[
                (misclassified['DICOM_phase'] == misclassified['TS_contrast']) & 
                (test_data['DICOM_phase'].notna())
                ][['MatchKey', 'contrast','ProtocolName', 'DICOM_phase', 'TS_contrast']]
print(f'TS predicted the correct DICOM label for {len(misclass_correct_dicom)}/{len(misclassified)} entries.')

misclass_correct_dicom

TS predicted the correct DICOM label for 23/873 entries.

/tmp/ipykernel_1510501/2811740420.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  misclass_correct_dicom = misclassified[

,MatchKey,contrast,ProtocolName,DICOM_phase,TS_contrast
490,NKI-d23231-00-0007_20100517_kalina09_0043.nii.gz,Arterial,Abdomen V 2mm,Portal,Portal
797,NKI-d23231-00-0005_20200128_kalina15_0059.nii.gz,Non-contrast,Abdomen A 1.5 B25f,Arterial,Arterial
1699,NKI-d23231-00-0192_20051202_giovanni01_0103.ni...,Non-contrast,Abdomen art 1.5 B30f,Arterial,Arterial
1771,NKI-d23231-00-0146_20190502_giovanni01_0179.ni...,Portal,Abd laat-art 1.0 I26f 2,Arterial,Arterial
1822,NKI-d23231-00-0152_20180116_giovanni01_0231.ni...,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
2657,NKI-d23231-00-0348_20131112_kalina01_0124.nii.gz,Portal,ABDOMEN A 1.0 FC01,Arterial,Arterial
2993,NKI-d23231-00-0873_20230822_kalina01_0511.nii.gz,Arterial,ABD PV Body 1.0 CE ABD PV,Portal,Portal
3099,NKI-d23231-00-0209_20081112_kalina99_0096.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
3282,NKI-d23231-00-0223_20210618_kalina99_0292.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
4289,NKI-d23231-00-0306_20160415_kalina99_1333.nii.gz,Portal,ABDOMEN A 1.0 FC01,Arterial,Arterial
4342,NKI-d23231-00-0308_20181122_kalina99_1389.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
4609,NKI-d23231-00-0332_20080502_kalina99_1679.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
4655,NKI-d23231-00-0335_20120328_kalina99_1736.nii.gz,Non-contrast,ABDOMEN A 1.0 FC02,Arterial,Arterial
5116,NKI-d23231-00-0382_20160203_kalina99_2225.nii.gz,Arterial,Abd-Veneus 3.0 B40f,Portal,Portal
5817,NKI-d23231-00-0449_20090618_kalina99_2985.nii.gz,Arterial,Abdomen V 1.5 B25f,Portal,Portal
6213,NKI-d23231-00-0484_20191031_kalina99_3398.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
6276,NKI-d23231-00-0507_20060904_kalina99_3474.nii.gz,Non-contrast,Lever A 2mm,Arterial,Arterial
6314,NKI-d23231-00-0511_20111025_kalina99_3525.nii.gz,Portal,Arterieel 3.0 B30f,Arterial,Arterial
7005,NKI-d23231-00-0610_20190313_kalina99_4330.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
7173,NKI-d23231-00-0655_20190307_kalina99_4521.nii.gz,Portal,Abdomen A 1.5 B25f,Arterial,Arterial
7949,NKI-d23231-00-0809_20170822_kalina99_5394.nii.gz,Arterial,Ven. fase 3.0 B31f,Portal,Portal
7950,NKI-d23231-00-0809_20171107_kalina99_5397.nii.gz,Arterial,Ven. fase 3.0 B31f,Portal,Portal
8146,NKI-d23231-00-0841_20180412_kalina99_5613.nii.gz,Arterial,Ven. fase 3.0 B31f,Portal,Portal

In [25]:
misclass_dicom = misclassified[
    (misclassified['TS_contrast'] != misclassified['DICOM_phase']) |
    (misclassified['DICOM_phase'].isna())
][['MatchKey', 'contrast','ProtocolName', 'DICOM_phase', 'TS_contrast']]

print('Number of entries where both DICOM and radiologists\' contrast != TS contrast:', len(misclass_dicom))
misclass_dicom.tail(5)

Number of entries where both DICOM and radiologists' contrast != TS contrast: 850

,MatchKey,contrast,ProtocolName,DICOM_phase,TS_contrast
8283,NKI-d23231-00-0879_20210929_kalina99_5775.nii.gz,Arterial,Abd laat-art 1.0 Bv38 2,Arterial,Portal
8309,NKI-d23231-00-0882_20220829_kalina99_5801.nii.gz,Arterial,Abd laat-art 1.0 Bv38 2,Arterial,Portal
8316,NKI-d23231-00-0887_20210825_kalina99_5811.nii.gz,Arterial,Abdomen A 1.5 B25f,Arterial,Portal
8320,NKI-d23231-00-0887_20220721_kalina99_5815.nii.gz,Arterial,Abdomen A 1.5 B25f,Arterial,Portal
8333,NKI-d23231-00-0888_20230801_kalina99_5830.nii.gz,Arterial,Abd laat-art 1.0 Bv38 2,Arterial,Portal

In [26]:
misclassified.is_liver_imaged.value_counts()

is_liver_imaged
Yes          824
Partially     49
Name: count, dtype: int64

### Visualizing the missclassifications

In [27]:
from monai.transforms import LoadImage, EnsureChannelFirst


folder_path = "/mnt/rhea/data_private/IRBd23-231/GEPNETs/ARTINET"


def data_load(folder_dir, data, group_col = 'contrast', num = 3, channel_first = True, load = True):
    samples = (data.groupby(group_col)
           .apply(lambda x: x.sample(n=min(num, len(x)), random_state=42))
           .reset_index()
                   )
    
    images = [] 
    
    if load == True:  
        loader = LoadImage(image_only=True)
        files = list(samples['file'])
        phases = list(samples['contrast'])
        for file in files:
            file_dir = os.path.join(folder_dir, PureWindowsPath(file).name)
            ct = loader(file_dir)
            if channel_first:
                ct = EnsureChannelFirst()(ct)

            ct = ct.numpy()
            images.append(ct)

    return samples, phases, images


samples, phases, misclass_images = data_load(folder_path, misclassified)

In [28]:
samples

,contrast,level_1,SubjectKeyRadiology,ExamDate,SegmentationBatch,NiiFile,SegNiiFile,file,is_liver_imaged,phase_timing,...,slice_thickness,DICOM_phase,file0,pi_time,phase,probability,pi_time_min,pi_time_max,stddev,TS_contrast
0,Arterial,5360,NKI-d23231-00-0865,2022-06-23,kalina99_5717,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0865_20220623_kalina99_5717.nii.gz,Yes,Just Right,...,1.0,Arterial,NET_5717_0000.nii.gz,78.88,portal_venous,1.0,72.90,82.48,4.1572,Portal
1,Arterial,2181,NKI-d23231-00-0227,2013-02-12,kalina99_0318,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0227_20130212_kalina99_0318.nii.gz,Yes,Too Early,...,1.0,Arterial,NET_0318_0000.nii.gz,64.20,portal_venous,1.0,59.08,67.98,3.1636,Portal
2,Arterial,5034,NKI-d23231-00-0795,2019-01-31,kalina99_5279,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0795_20190131_kalina99_5279.nii.gz,Yes,Just Right,...,1.5,Arterial,NET_5279_0000.nii.gz,64.66,portal_venous,1.0,60.42,69.63,3.5250,Portal
3,Non-contrast,1482,NKI-d23231-00-0170,2006-04-05,kalina99_0444,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0170_20060405_kalina99_0444.nii.gz,Yes,Just Right,...,1.5,NaN,NET_0444_0000.nii.gz,82.13,portal_venous,1.0,77.66,87.60,3.8453,Portal
4,Non-contrast,1596,NKI-d23231-00-0193,2016-10-12,kalina99_0660,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0193_20161012_kalina99_0660.nii.gz,Yes,Too Early,...,1.0,NaN,NET_0660_0000.nii.gz,77.88,portal_venous,1.0,75.51,80.96,1.7601,Portal
5,Non-contrast,4160,NKI-d23231-00-0532,2015-08-18,kalina99_3669,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0532_20150818_kalina99_3669.nii.gz,Yes,Just Right,...,1.5,Portal,NET_3669_0000.nii.gz,81.06,portal_venous,1.0,78.78,83.38,1.7551,Portal
6,Portal,243,NKI-d23231-00-0024,2021-04-23,kalina08_0039,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0024_20210423_kalina08_0039.nii.gz,Yes,Just Right,...,1.0,NaN,NET_0039_0000.nii.gz,56.71,arterial_late,0.7,50.85,60.37,3.3814,Arterial
7,Portal,4551,NKI-d23231-00-0653,2020-10-14,kalina99_4513,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0653_20201014_kalina99_4513.nii.gz,Yes,Just Right,...,1.0,NaN,NET_4513_0000.nii.gz,59.04,arterial_late,0.7,56.94,60.34,1.2221,Arterial
8,Portal,4487,NKI-d23231-00-0615,2017-10-21,kalina99_4355,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...,NKI-d23231-00-0615_20171021_kalina99_4355.nii.gz,Yes,Just Right,...,1.0,NaN,NET_4355_0000.nii.gz,57.09,arterial_late,0.7,51.56,60.78,3.4093,Arterial

In [29]:
misclass_images[4].shape

(1, 512, 512, 145)

In [ ]:
def show_slices_per_class(images, center=50, width=300):

    def window_ct(img, center, width):
        low = center - width/2
        high = center + width/2
        return img.clip(low, high)


    class_ranges = {
        "Arterial": range(0, 3),
        "Non-contrast": range(3, 6),
        "Portal": range(6, 9)
    }

    for cls_name, indices in class_ranges.items():

        if cls_name == 'Portal':
            z = 50
        else:
            z = int(np.mean([images[i].shape[3] for i in indices]))- 30

        plt.figure(figsize=(15,5))
        for j, i in enumerate(indices):
            img = images[i][0, :, :, z]
            plt.subplot(1, 3, j+1)
            plt.imshow(np.rot90(window_ct(img, center, width),k=1), cmap="gray")
            plt.title(f"{cls_name} image {i}, slice {z}")
            plt.axis("off")
        plt.show()

show_slices_per_class(misclass_images)

SyntaxError: invalid character '§' (U+00A7) (2721995884.py, line 20)

## Phase + Timing Classification Results

In [ ]:
# merged_data.loc[merged_data["contrast"] == "Portal","phase_timing"] = "Just Right"

# merged_data["phase_timing_combined"] = (merged_data["contrast"].str.cat(merged_data["phase_timing"], sep=" "))
# merged_data["TS_phase_timing_combined"] = (merged_data["TS_contrast"].str.cat(merged_data["TS_timing"], sep=" "))

# print(merged_data["phase_timing_combined"].value_counts())
# print("\n")
# print(merged_data["TS_phase_timing_combined"].value_counts())


# contrast_correct = merged_data[merged_data["contrast"] == merged_data["TS_contrast"]].copy()

# y_true = le.fit_transform(contrast_correct["phase_timing"])
# y_pred = le.fit_transform(contrast_correct['TS_timing'])

# print('Timing classification accuracy:', round(accuracy_score(y_true, y_pred),3))
# print("Classification report:\n", classification_report(y_true, y_pred, target_names=le.classes_))

# print("Confusion matrix:")
# pd.crosstab(
#     contrast_correct["phase_timing"],
#     contrast_correct['TS_timing'],
#     margins=True
# )

phase_timing_combined
Portal Just Right            3133
Arterial Just Right          1365
Arterial Too Early            661
Arterial Too Late              97
Portal Too Early               97
Portal Too Late                51
Non-contrast Non-contrast      42
Name: count, dtype: int64


TS_phase_timing_combined
Portal Just Right            3922
Arterial Too Late            1482
Non-contrast Non-contrast      30
Arterial Too Early             12
Name: count, dtype: int64

## Time Interval Estimation

In [51]:
contrast_data = test_data[test_data["contrast"] !='Non-contrast'] # ignore the NC images 

cols = ['SubjectKeyRadiology', 'ExamDate', 'contrast', 'phase_timing', 'TS_contrast', 'phase', 'DICOM_phase',
        'AcquisitionTime', 'AcquisitionTime_sec', 'pi_time','SliceThickness', 'ProtocolName', 'ConvolutionKernel',
        'pi_time_min', 'pi_time_max', 'stddev', 'file', 'BodyPartExamined']

contrast_data=test_data.sort_values(by=['SubjectKeyRadiology', 'ExamDate','AcquisitionTime'], ascending=[True, True, True]).reset_index()
contrast_data[cols]

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
0,NKI-d23231-00-0001,2006-09-20,Portal,Too Early,Portal,portal_venous,NaN,12:07:42.451000,43662.45100,85.59,1.5,Abdomen 1.5 B30f,B30f,82.12,93.46,4.2121,NET_0045_0000.nii.gz,ABDOMEN
1,NKI-d23231-00-0001,2007-06-08,Non-contrast,Non-contrast,Non-contrast,native,Non-contrast,11:45:35.004490,42335.00449,2.26,1.5,Lever -C 1.5 B25f,B25f,-0.19,3.79,1.3133,NET_0032_0000.nii.gz,ABDOMEN
2,NKI-d23231-00-0001,2007-06-08,Portal,Just Right,Portal,portal_venous,NaN,11:47:19.223200,42439.22320,82.55,1.5,Abdomen +C 1.5 B30f,B30f,80.15,83.99,1.3290,NET_0023_0000.nii.gz,ABDOMEN
3,NKI-d23231-00-0001,2007-08-15,Portal,Too Early,Portal,portal_venous,NaN,11:51:28.000000,42688.00000,65.44,2.0,PANCREAS 2MM.,B,62.05,67.68,1.8933,NET_0002_0000.nii.gz,PANCREAS
4,NKI-d23231-00-0001,2007-08-15,Portal,Just Right,Portal,portal_venous,Portal,11:51:53.000000,42713.00000,74.22,3.0,PORTAAL 3MM.,B,71.60,77.96,2.7185,NET_0007_0000.nii.gz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8328,NKI-d23231-00-0888,2022-04-20,Portal,Just Right,Portal,portal_venous,Portal,15:13:16.119320,54796.11932,80.39,1.5,Abdomen V 1.5 B25f,B25f,78.27,82.66,1.4937,NET_5827_0000.nii.gz,ABDOMEN
8329,NKI-d23231-00-0888,2023-04-24,Arterial,Just Right,Arterial,arterial_late,Arterial,12:05:45.561000,43545.56100,59.19,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.14,61.54,1.8509,NET_5828_0000.nii.gz,ABDOMEN
8330,NKI-d23231-00-0888,2023-04-24,Portal,Just Right,Portal,portal_venous,NaN,12:06:20.138000,43580.13800,77.28,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,74.66,78.94,1.6271,NET_5829_0000.nii.gz,ABDOMEN
8331,NKI-d23231-00-0888,2023-08-01,Arterial,Just Right,Portal,portal_venous,Arterial,11:43:20.650000,42200.65000,63.08,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,60.32,64.76,1.5287,NET_5830_0000.nii.gz,ABDOMEN
8332,NKI-d23231-00-0888,2023-08-01,Portal,Just Right,Portal,portal_venous,NaN,11:43:50.042000,42230.04200,73.31,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,72.83,73.69,0.2884,NET_5831_0000.nii.gz,ABDOMEN

### Only contrast data

In [52]:
contrast_data = test_data[test_data["contrast"] !='Non-contrast'] # ignore the NC images as they are only 42 
cols = ['SubjectKeyRadiology', 'ExamDate', 'contrast', 'phase_timing', 'TS_contrast', 'phase', 'DICOM_phase',
        'AcquisitionTime', 'AcquisitionTime_sec', 'pi_time','SliceThickness', 'ProtocolName', 'ConvolutionKernel',
        'pi_time_min', 'pi_time_max', 'stddev', 'file', 'BodyPartExamined']

contrast_data=contrast_data.sort_values(by=['SubjectKeyRadiology', 'ExamDate','AcquisitionTime'], ascending=[True, True, True]).reset_index()
contrast_data[cols]

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
0,NKI-d23231-00-0001,2006-09-20,Portal,Too Early,Portal,portal_venous,NaN,12:07:42.451000,43662.45100,85.59,1.5,Abdomen 1.5 B30f,B30f,82.12,93.46,4.2121,NET_0045_0000.nii.gz,ABDOMEN
1,NKI-d23231-00-0001,2007-06-08,Portal,Just Right,Portal,portal_venous,NaN,11:47:19.223200,42439.22320,82.55,1.5,Abdomen +C 1.5 B30f,B30f,80.15,83.99,1.3290,NET_0023_0000.nii.gz,ABDOMEN
2,NKI-d23231-00-0001,2007-08-15,Portal,Too Early,Portal,portal_venous,NaN,11:51:28.000000,42688.00000,65.44,2.0,PANCREAS 2MM.,B,62.05,67.68,1.8933,NET_0002_0000.nii.gz,PANCREAS
3,NKI-d23231-00-0001,2007-08-15,Portal,Just Right,Portal,portal_venous,Portal,11:51:53.000000,42713.00000,74.22,3.0,PORTAAL 3MM.,B,71.60,77.96,2.7185,NET_0007_0000.nii.gz,NaN
4,NKI-d23231-00-0001,2008-03-17,Arterial,Too Early,Arterial,arterial_late,Arterial,14:31:3.045110,52263.04511,53.85,1.5,Lever A 1.5 B25f,B25f,48.70,58.97,3.3563,NET_0037_0000.nii.gz,ABDOMEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6263,NKI-d23231-00-0888,2022-04-20,Portal,Just Right,Portal,portal_venous,Portal,15:13:16.119320,54796.11932,80.39,1.5,Abdomen V 1.5 B25f,B25f,78.27,82.66,1.4937,NET_5827_0000.nii.gz,ABDOMEN
6264,NKI-d23231-00-0888,2023-04-24,Arterial,Just Right,Arterial,arterial_late,Arterial,12:05:45.561000,43545.56100,59.19,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.14,61.54,1.8509,NET_5828_0000.nii.gz,ABDOMEN
6265,NKI-d23231-00-0888,2023-04-24,Portal,Just Right,Portal,portal_venous,NaN,12:06:20.138000,43580.13800,77.28,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,74.66,78.94,1.6271,NET_5829_0000.nii.gz,ABDOMEN
6266,NKI-d23231-00-0888,2023-08-01,Arterial,Just Right,Portal,portal_venous,Arterial,11:43:20.650000,42200.65000,63.08,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,60.32,64.76,1.5287,NET_5830_0000.nii.gz,ABDOMEN
6267,NKI-d23231-00-0888,2023-08-01,Portal,Just Right,Portal,portal_venous,NaN,11:43:50.042000,42230.04200,73.31,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,72.83,73.69,0.2884,NET_5831_0000.nii.gz,ABDOMEN

In [53]:
# ASK
print('Same acquisition time, different time prediction due to reconstruction kernel')
contrast_data[cols][contrast_data.SubjectKeyRadiology == 'NKI-d23231-00-0281'].head(2)

Same acquisition time, different time prediction due to reconstruction kernel

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
2556,NKI-d23231-00-0281,2014-05-20,Portal,Just Right,Portal,portal_venous,NaN,12:31:15.181500,45075.18150,71.83,1.5,ThxAbd 1.5 B25f,B25f,69.96,74.97,1.8208,NET_0953_0000.nii.gz,CHEST
2557,NKI-d23231-00-0281,2014-05-20,Portal,Just Right,Portal,portal_venous,NaN,12:31:15.183190,45075.18319,70.51,3.0,ThxAbd 3.0 B31f,B31f,67.65,72.06,1.5080,NET_0954_0000.nii.gz,CHEST

In [57]:
def estimate_time_interval(paired_data):

    pairs = []

    # Per exam
    for (patient_id, exam_date), group in paired_data.groupby(
        ["SubjectKeyRadiology", "ExamDate"]
    ):

        group = group.sort_values("AcquisitionTime_sec")

        arterial = group[group["contrast"] == "Arterial"]
        portal = group[group["contrast"] == "Portal"]

        if arterial.empty or portal.empty:
            continue

        # For each arterial, pair with ALL future portal variants

        for _, a_row in arterial.iterrows():

            a_time = a_row["AcquisitionTime_sec"]
            a_pi_time = a_row["pi_time"]
            future_portals = portal[portal["AcquisitionTime_sec"] > a_time]

            if future_portals.empty:
                continue

            a_phase = a_row["phase_timing"]

            # Preserve multiple kernel reconstructions

            for _, p_row in future_portals.iterrows():

                p_time = p_row["AcquisitionTime_sec"]
                p_pi_time = p_row["pi_time"]
                interval = p_time - a_time
                TS_interval = p_pi_time - a_pi_time

                if interval <= 0 or TS_interval <= 0:
                    continue

                p_phase = p_row["phase_timing"]
                pairs.append({

                    "SubjectKeyRadiology": patient_id,
                    "ExamDate": exam_date,
        
                    "arterial_timing": a_phase,
                    "portal_timing": p_phase,

                    # DICOM acquisition time interval
                    "time_interval": interval,

                    # TS predicted time interval
                    "TS_time_interval": TS_interval

                })

    return pd.DataFrame(pairs)

In [58]:
time_interval_results =  estimate_time_interval(contrast_data)
time_interval_results

,SubjectKeyRadiology,ExamDate,arterial_timing,portal_timing,time_interval,TS_time_interval
0,NKI-d23231-00-0002,2015-12-01,Too Late,Too Early,0.00519,0.23
1,NKI-d23231-00-0005,2010-02-04,Too Early,Just Right,53.64779,37.96
2,NKI-d23231-00-0005,2012-06-18,Too Early,Too Early,33.40000,25.52
3,NKI-d23231-00-0005,2022-05-11,Just Right,Just Right,30.84280,41.10
4,NKI-d23231-00-0005,2022-10-17,Just Right,Just Right,32.75200,11.91
...,...,...,...,...,...,...
2056,NKI-d23231-00-0887,2023-05-24,Just Right,Just Right,31.57800,32.54
2057,NKI-d23231-00-0887,2023-08-30,Just Right,Just Right,28.90000,23.61
2058,NKI-d23231-00-0888,2022-04-20,Just Right,Just Right,31.78189,23.45
2059,NKI-d23231-00-0888,2023-04-24,Just Right,Just Right,34.57700,18.09
2060,NKI-d23231-00-0888,2023-08-01,Just Right,Just Right,29.39200,10.23

In [61]:
# time_interval_results.time_interval.info()

from sklearn.metrics import root_mean_squared_error, mean_absolute_error

print("MAE:", mean_absolute_error(time_interval_results.time_interval,time_interval_results.TS_time_interval))
print("RMSE:", root_mean_squared_error(time_interval_results.time_interval,time_interval_results.TS_time_interval))

MAE: 20.71660710334786
RMSE: 26.482406717583054

In [ ]:
# # def time_to_seconds(t):
# #     minutes, seconds = t.split(':')
# #     return int(minutes) * 60 + float(seconds)

# unique_keys = ["SubjectKeyRadiology"
#                ,"ExamDate"
#                ,"ConvolutionKernel"
#                , 'SliceThickness'
#                , 'BodyPartExamined'
#                 ]

# # contrast_data['AcquisitionTime_sec'] = contrast_data['AcquisitionTime'].apply(time_to_seconds)

# contrast_data["time_interval"] = (
#     contrast_data
#     .groupby(unique_keys)["AcquisitionTime_sec"]
#     .diff()
#     .shift(-1)
#     .ffill(limit = 1)
# )

# contrast_data["TS_time_interval"] = (
#     contrast_data
#     .groupby(unique_keys)["pi_time"]
#     .diff()
#     .shift(-1)
#     .ffill(limit = 1)
#     )

In [62]:
# contrast_data['TS_time_interval'] = contrast_data['TS_time_interval'].apply(lambda x: abs(x))
# contrast_data['time_interval'] = contrast_data['time_interval'].apply(lambda x: abs(x))

# cols.insert(9,'time_interval')
# cols.insert(10, 'TS_time_interval')

# contrast_data[cols][contrast_data.SubjectKeyRadiology == 'NKI-d23231-00-0281']

In [63]:
# ASK - more than 3 entries per exam (due to different protocols or incorrect NC labels => different ordering => different intervals)

unique_keys = ["SubjectKeyRadiology"
               ,"ExamDate"
               ,"ConvolutionKernel"
               , 'SliceThickness'
               , 'BodyPartExamined'
                ]

multi_phase = (
    contrast_data
    .groupby(unique_keys)
    .filter(lambda x: len(x) > 2)
)

multi_phase[cols].sort_values(
        by=['SubjectKeyRadiology', 'ExamDate', 'AcquisitionTime'])

,SubjectKeyRadiology,ExamDate,contrast,phase_timing,TS_contrast,phase,DICOM_phase,AcquisitionTime,AcquisitionTime_sec,pi_time,SliceThickness,ProtocolName,ConvolutionKernel,pi_time_min,pi_time_max,stddev,file,BodyPartExamined
3852,NKI-d23231-00-0420,2014-07-04,Portal,Just Right,Portal,portal_venous,Arterial,10:19:18.642500,37158.64250,66.69,3.0,Arterieel 3.0 B30f,B30f,65.42,67.38,0.6966,NET_2725_0000.nii.gz,ABDOMEN
3853,NKI-d23231-00-0420,2014-07-04,Portal,Just Right,Portal,portal_venous,Portal,10:19:51.939490,37191.93949,75.15,3.0,Veneus 3.0 B30f,B30f,71.16,77.74,2.4462,NET_2727_0000.nii.gz,ABDOMEN
3854,NKI-d23231-00-0420,2014-07-04,Portal,Too Late,Portal,portal_venous,Portal,10:23:47.518010,37427.51801,69.71,3.0,Veneus laat 3.0 B30f,B30f,66.32,73.65,2.5375,NET_2728_0000.nii.gz,ABDOMEN
3894,NKI-d23231-00-0424,2015-05-01,Arterial,Just Right,Portal,portal_venous,Arterial,11:51:56.280520,42716.28052,62.93,3.0,Arterieel 3.0 B30f,B30f,60.98,63.98,1.0157,NET_0183_0000.nii.gz,ABDOMEN
3895,NKI-d23231-00-0424,2015-05-01,Portal,Just Right,Portal,portal_venous,Portal,11:52:32.101970,42752.10197,76.13,3.0,Veneus 3.0 B30f,B30f,74.77,77.10,0.8490,NET_2786_0000.nii.gz,ABDOMEN
3896,NKI-d23231-00-0424,2015-05-01,Portal,Too Late,Portal,portal_venous,Portal,11:55:42.205980,42942.20598,85.98,3.0,Veneus laat 3.0 B30f,B30f,84.83,87.78,1.0210,NET_2787_0000.nii.gz,ABDOMEN
4591,NKI-d23231-00-0535,2019-09-18,Arterial,Just Right,Arterial,arterial_late,Arterial,11:44:33.167000,42273.16700,53.58,1.0,Abd laat-art 1.0 I26f 2 iMAR,I26f\2,47.59,59.49,4.9791,NET_3754_0000.nii.gz,ABDOMEN
4592,NKI-d23231-00-0535,2019-09-18,Arterial,Just Right,Arterial,arterial_late,Arterial,11:44:33.167000,42273.16700,53.84,1.0,Abd laat-art 1.0 I26f 2,I26f\2,48.53,59.80,4.8582,NET_3755_0000.nii.gz,ABDOMEN
4593,NKI-d23231-00-0535,2019-09-18,Portal,Just Right,Portal,portal_venous,NaN,11:45:11.105000,42311.10500,73.17,1.0,Abdomen 1.0 I26f 2 iMAR,I26f\2,70.52,75.75,1.8035,NET_3756_0000.nii.gz,ABDOMEN
4594,NKI-d23231-00-0535,2019-09-18,Portal,Just Right,Portal,portal_venous,NaN,11:45:11.105000,42311.10500,71.00,1.0,Abdomen 1.0 I26f 2,I26f\2,69.38,73.31,1.3085,NET_3757_0000.nii.gz,ABDOMEN
4606,NKI-d23231-00-0535,2022-07-19,Arterial,Just Right,Arterial,arterial_late,Arterial,14:01:30.540000,50490.54000,57.71,1.0,Abd laat-art 1.0 Bv38 2 iMAR,Bv38f\2,50.40,62.33,4.2817,NET_3769_0000.nii.gz,ABDOMEN
4607,NKI-d23231-00-0535,2022-07-19,Arterial,Just Right,Portal,portal_venous,Arterial,14:01:30.540000,50490.54000,61.12,1.0,Abd laat-art 1.0 Bv38 2,Bv38f\2,56.96,64.00,2.3650,NET_3770_0000.nii.gz,ABDOMEN
4609,NKI-d23231-00-0535,2022-07-19,Portal,Just Right,Portal,portal_venous,NaN,14:02:7.336000,50527.33600,73.31,1.0,Abdomen 1.0 Bv38 2,Bv38f\2,71.97,74.31,0.7583,NET_3772_0000.nii.gz,ABDOMEN
5714,NKI-d23231-00-0793,2017-10-03,Arterial,Just Right,Arterial,arterial_early,NaN,12:27:31.279000,44851.27900,29.57,3.0,Art.Lever+thora 3.0 B40f,B40f,27.00,31.50,1.4892,NET_0439_0000.nii.gz,ABDOMEN
5715,NKI-d23231-00-0793,2017-10-03,Portal,Just Right,Portal,portal_venous,Portal,12:27:48.777000,44868.77700,68.96,3.0,Abd-Veneus 3.0 B40f,B40f,67.37,72.08,1.6875,NET_5270_0000.nii.gz,ABDOMEN
5716,NKI-d23231-00-0793,2017-10-03,Portal,Too Late,Portal,portal_venous,Portal,12:31:1.331000,45061.33100,66.96,3.0,Lever-Laat ven 3.0 B40f,B40f,65.98,68.29,0.8409,NET_5273_0000.nii.gz,ABDOMEN